

package imakante.com;

import imakante.com.*;
import javax.swing.JOptionPane;


public class mainFrame extends javax.swing.JFrame {
    
    /** Creates new form mainFrame */
    public mainFrame() {
        initComponents();
        pubMain.mainJFrame = this;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jEditorPane1 = new javax.swing.JEditorPane();
        jToolBar1 = new javax.swing.JToolBar();
        jLoginBtn = new javax.swing.JButton();
        jLogoutBtn = new javax.swing.JButton();
        jSepLabel = new javax.swing.JLabel();
        jSalaryBtn = new javax.swing.JButton();
        jSalesBtn = new javax.swing.JButton();
        jAccBtn = new javax.swing.JButton();
        jSepLabel2 = new javax.swing.JLabel();
        jExitBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFileMenu = new javax.swing.JMenu();
        jLoginItem = new javax.swing.JMenuItem();
        jLogoutItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jQuitItem = new javax.swing.JMenuItem();
        jOptionsMenu = new javax.swing.JMenu();
        jFirmItem = new javax.swing.JMenuItem();
        jUserItem = new javax.swing.JMenuItem();
        jModuleMenu = new javax.swing.JMenu();
        jSalaryItem = new javax.swing.JMenuItem();
        jSalesItem = new javax.swing.JMenuItem();
        jAccItem = new javax.swing.JMenuItem();
        jHelpMenu = new javax.swing.JMenu();
        jHelpItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jAboutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\u0418\u043c\u0430\u043a\u0430\u043d\u0442\u0435 \u0415\u0420\u041f");
        jLoginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imakante/images/Login2.png")));
        jLoginBtn.setToolTipText("\u0412\u0445\u043e\u0434 \u0432 \u0441\u0438\u0441\u0442\u0435\u043c\u0430\u0442\u0430");
        jLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginAction(evt);
            }
        });

        jToolBar1.add(jLoginBtn);

        jLogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imakante/images/Logout.png")));
        jLogoutBtn.setToolTipText("\u041f\u0440\u0435\u043a\u044a\u0441\u043d\u0438 \u0432\u0440\u044a\u0437\u043a\u0430\u0442\u0430 \u0441 \u0431\u0430\u0437\u0430\u0442\u0430");
        jLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutAction(evt);
            }
        });

        jToolBar1.add(jLogoutBtn);

        jSepLabel.setMaximumSize(new java.awt.Dimension(4, 32));
        jSepLabel.setMinimumSize(new java.awt.Dimension(4, 32));
        jSepLabel.setPreferredSize(new java.awt.Dimension(4, 32));
        jSepLabel.setRequestFocusEnabled(false);
        jSepLabel.setVerifyInputWhenFocusTarget(false);
        jSepLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jToolBar1.add(jSepLabel);

        jSalaryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imakante/images/Salary2.png")));
        jSalaryBtn.setToolTipText("\u041b\u0438\u0447\u0435\u043d \u0441\u044a\u0441\u0442\u0430\u0432");
        jToolBar1.add(jSalaryBtn);

        jSalesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imakante/images/Sales2.png")));
        jSalesBtn.setToolTipText("\u0420\u0435\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u044f (\u0441\u043a\u043b\u0430\u0434)");
        jToolBar1.add(jSalesBtn);

        jAccBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imakante/images/Accounts2.png")));
        jAccBtn.setToolTipText("\u0421\u0447\u0435\u0442\u043e\u0432\u043e\u0434\u0441\u0442\u0432\u043e");
        jToolBar1.add(jAccBtn);

        jSepLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jSepLabel2.setMaximumSize(new java.awt.Dimension(4, 32));
        jSepLabel2.setMinimumSize(new java.awt.Dimension(4, 32));
        jSepLabel2.setPreferredSize(new java.awt.Dimension(4, 32));
        jToolBar1.add(jSepLabel2);

        jExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imakante/images/Exit.png")));
        jExitBtn.setToolTipText("\u041a\u0440\u0430\u0439 \u043d\u0430 \u0440\u0430\u0431\u043e\u0442\u0430");
        jExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        jToolBar1.add(jExitBtn);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jFileMenu.setText("\u0421\u0438\u0441\u0442\u0435\u043c\u0430");
        jLoginItem.setText("\u0412\u0445\u043e\u0434...");
        jLoginItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginAction(evt);
            }
        });

        jFileMenu.add(jLoginItem);

        jLogoutItem.setText("\u0418\u0437\u0445\u043e\u0434");
        jLogoutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutAction(evt);
            }
        });

        jFileMenu.add(jLogoutItem);

        jFileMenu.add(jSeparator1);

        jQuitItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imakante/images/quit.gif")));
        jQuitItem.setText("\u041a\u0440\u0430\u0439");
        jQuitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        jFileMenu.add(jQuitItem);

        jMenuBar1.add(jFileMenu);

        jOptionsMenu.setText("\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438");
        jFirmItem.setText("\u0424\u0438\u0440\u043c\u0430...");
        jFirmItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirmItemAction(evt);
            }
        });

        jOptionsMenu.add(jFirmItem);

        jUserItem.setText("\u041f\u043e\u0442\u0440\u0435\u0431\u0438\u0442\u0435\u043b\u0438...");
        jOptionsMenu.add(jUserItem);

        jMenuBar1.add(jOptionsMenu);

        jModuleMenu.setText("\u041c\u043e\u0434\u0443\u043b\u0438");
        jSalaryItem.setText("\u041b\u0438\u0447\u0435\u043d \u0441\u044a\u0441\u0442\u0430\u0432...");
        jModuleMenu.add(jSalaryItem);

        jSalesItem.setText("\u0420\u0435\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u044f (\u0441\u043a\u043b\u0430\u0434)...");
        jModuleMenu.add(jSalesItem);

        jAccItem.setText("\u0421\u0447\u0435\u0442\u043e\u0432\u043e\u0434\u0441\u0442\u0432\u043e...");
        jModuleMenu.add(jAccItem);

        jMenuBar1.add(jModuleMenu);

        jHelpMenu.setText("\u041f\u043e\u043c\u043e\u0449");
        jHelpItem.setText("\u041f\u043e\u043c\u043e\u0449\u043d\u0430 \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f...");
        jHelpMenu.add(jHelpItem);

        jHelpMenu.add(jSeparator2);

        jAboutItem.setText("\u0417\u0430 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u0430\u0442\u0430...");
        jHelpMenu.add(jAboutItem);

        jMenuBar1.add(jHelpMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFirmItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirmItemAction
        dlgFirms dlg = new dlgFirms(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_jFirmItemAction

    private void jLogoutAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutAction
        if (pubMain.disconnect())
            JOptionPane.showMessageDialog(null,"Връзката с базата прекъсната !","ИМАКАНТЕ",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLogoutAction

    private void jLoginAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginAction
        if (pubMain.connect())
            JOptionPane.showMessageDialog(null,"Успешен вход в базата !","ИМАКАНТЕ",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLoginAction

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jExitActionPerformed
    

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    String sysLook = javax.swing.UIManager.getSystemLookAndFeelClassName();
                    javax.swing.UIManager.setLookAndFeel(sysLook);
                } catch (Exception err) {
                    System.err.println("Exception: " + err.getMessage());
                }
                new mainFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAboutItem;
    private javax.swing.JButton jAccBtn;
    private javax.swing.JMenuItem jAccItem;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JButton jExitBtn;
    private javax.swing.JMenu jFileMenu;
    private javax.swing.JMenuItem jFirmItem;
    private javax.swing.JMenuItem jHelpItem;
    private javax.swing.JMenu jHelpMenu;
    private javax.swing.JButton jLoginBtn;
    private javax.swing.JMenuItem jLoginItem;
    private javax.swing.JButton jLogoutBtn;
    private javax.swing.JMenuItem jLogoutItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jModuleMenu;
    private javax.swing.JMenu jOptionsMenu;
    private javax.swing.JMenuItem jQuitItem;
    private javax.swing.JButton jSalaryBtn;
    private javax.swing.JMenuItem jSalaryItem;
    private javax.swing.JButton jSalesBtn;
    private javax.swing.JMenuItem jSalesItem;
    private javax.swing.JLabel jSepLabel;
    private javax.swing.JLabel jSepLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem jUserItem;
    // End of variables declaration//GEN-END:variables
    
}
