package imakante.com;

import imakante.sales.aeDocumentFacade;
import java.util.*;

public class simpleReport extends javax.swing.JFrame {
  
    private int docType;
    private HashMap inputFiltrs;
   
   
    
    /** Creates new form simpleReport */
    public simpleReport(HashMap inputfilters,int doctype) 
    {
        docType = doctype;
        inputFiltrs = inputfilters;
        
        initComponents();
        selectDocument(docType);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanelControl = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanelData = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        jPanelControl.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        jPanelControl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelControl.setMinimumSize(new java.awt.Dimension(600, 50));
        jPanelControl.setPreferredSize(new java.awt.Dimension(600, 50));
        jButton1.setText("\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430 \u043d\u0430 \u043a\u043e\u043b\u043e\u043d\u0438\u0442\u0435");
        jPanelControl.add(jButton1);

        getContentPane().add(jPanelControl, java.awt.BorderLayout.CENTER);

        jPanelData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelData.setMinimumSize(new java.awt.Dimension(650, 400));
        jPanelData.setPreferredSize(new java.awt.Dimension(600, 400));
        org.jdesktop.layout.GroupLayout jPanelDataLayout = new org.jdesktop.layout.GroupLayout(jPanelData);
        jPanelData.setLayout(jPanelDataLayout);
        jPanelDataLayout.setHorizontalGroup(
            jPanelDataLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 646, Short.MAX_VALUE)
        );
        jPanelDataLayout.setVerticalGroup(
            jPanelDataLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 396, Short.MAX_VALUE)
        );
        getContentPane().add(jPanelData, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
  
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simpleReport(null,1);
              
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanelControl;
    private javax.swing.JPanel jPanelData;
    // End of variables declaration//GEN-END:variables


 
 private void selectDocument(int doctype)
 {
     switch(doctype)
     {
         case aeDocumentFacade.BRAK:
         {
             break;
         }
         case aeDocumentFacade.FAKTURA_DANACHNA:
         {
             break;
         }
         case aeDocumentFacade.FAKTURA_OPROSTENA:
         {
             break;
         }
         case aeDocumentFacade.NAREZDANE_ZA_PREHVYRQNE:
         {
              break;
         }
         case aeDocumentFacade.OFERTA:
         {
              break;
         }
         case aeDocumentFacade.PREDAVATELNA_RAZPISKA:
         {
             break;
         }
         case aeDocumentFacade.PRIEMATELNA_RAZPISKA:
         {
             break;
         }
         case aeDocumentFacade.PROFORMA_FAKTURA:
         {
             break;
         }
         case aeDocumentFacade.PROTOKOL_LIPSA:
         {
             break;
         }
         case  aeDocumentFacade.RAZPISKA_ZA_VRYSHTANE:
         {
             break;
         }
     }// end switch
     
     
 }
 
 
}
