

package imakante.sales;


import java.awt.event.WindowListener;
import java.awt.print.PrinterException;
import java.sql.*;
import imakante.com.*;
import imakante.com.vcomponents.*;
import javax.print.PrintException;
import javax.swing.*;
import java.text.MessageFormat;


public class FrmDocumentFacade extends  imakante.com.vcomponents.iInternalFrame implements WindowListener
{

    public FrmDocumentFacade(String title, int user, int level, int pricelist, int doctype,int storagedocdacade) // TEST   imakante.com.vcomponents.iFrame frame,
    {
        super(title);
       // myframe = frame; 
        this.userDocFacade = user;
       this.levelDocFacade = level;
       this.priceList = pricelist;
       this.docType = doctype;
       this.storageDocFacade= storagedocdacade;
       
        prepareConn();     // zapazva connection
        constructGroupDB(); // inicializira class otgovarq6t za vryzkata s DB
       initTable();
        initComponents();
        fr.addWindowListener(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextCod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextAnLevel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonNew = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jButtonPrnReport = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jButtonDeleteAll = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(452, 45));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.getViewport().add(table);
        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(448, 37));
        jLabel1.setText("\u041a\u043e\u0434:");
        jPanel4.add(jLabel1);

        jTextCod.setPreferredSize(new java.awt.Dimension(45, 20));
        jPanel4.add(jTextCod);

        jLabel2.setText("\u0418\u043c\u0435:");
        jPanel4.add(jLabel2);

        jTextName.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel4.add(jTextName);

        jLabel3.setText("\u0410\u043d\u0430\u043b\u0438\u0442\u0438\u0447\u043d\u0438 \u043d\u0438\u0432\u0430:");
        jPanel4.add(jLabel3);

        jTextAnLevel.setPreferredSize(new java.awt.Dimension(45, 20));
        jPanel4.add(jTextAnLevel);

        jButton1.setText("\u0422\u044a\u0440\u0441\u0435\u043d\u0435");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.add(jButton1);

        jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 825, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 10, Short.MAX_VALUE)
        );
        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(801, 37));
        jButtonNew.setText("\u041d\u043e\u0432");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonNew);

        jButtonEdit.setText("\u0420\u0435\u0434\u0430\u043a\u0446\u0438\u044f");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonEdit);

        jButtonPrint.setText("\u041f\u0435\u0447\u0430\u0442");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonPrint);

        jButtonPrnReport.setText("\u041f\u0435\u0447\u0430\u0442 \u0440\u0435\u043f\u043e\u0440\u0442");
        jPanel3.add(jButtonPrnReport);

        jButtonDel.setText("\u0418\u0437\u0442\u0440\u0438\u0432\u0430\u043d\u0435");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonDel);

        jButtonRefresh.setText("\u0412\u0441\u0438\u0447\u043a\u0438 \u0437\u0430\u043f\u0438\u0441\u0438");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonRefresh);

        jButtonDeleteAll.setText("\u0418\u0437\u0442\u0440\u0438\u0432\u0430\u043d\u0435 \u043d\u0430 \u0442\u0430\u0431\u043b\u0438\u0446\u0430");
        jPanel3.add(jButtonDeleteAll);

        jButtonClose.setText("\u0417\u0430\u0442\u0432\u0430\u0440\u044f\u043d\u0435");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonClose);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
// TODO add your handling code here:
      
    }//GEN-LAST:event_formInternalFrameClosed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
// TODO add your handling code here:
        
        try
        {
        MessageFormat headerFormat = new MessageFormat("Group");
        MessageFormat footerFormat = new MessageFormat("Page. "+"- {0} -"+" IMAKANTE' ");
        table.print(JTable.PrintMode.FIT_WIDTH, headerFormat, footerFormat);
        }
        catch(PrinterException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        try
        {
         String searchCod = jTextCod.getText();
         String searchName = jTextName.getText();
         int searchAnLevel = Integer.parseInt(jTextAnLevel.getText());
        // rs = countriesT.searchRecords(getNom(),searchCod,searchName,searchAnLevel);
         jScrollPane1.remove(table);
         model = new imakante.com.CustomTableModel(conn,rs, null);
         table = new imakante.com.CustomTable(model);
         jScrollPane1.getViewport().add(table);
         jScrollPane1.repaint();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
// TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
// TODO add your handling code here:
        if(table.getSelectedRow() != -1)
        {
            setRow(table.getSelectedRow());
            setID_DocFacade((Integer)table.getValueAt(getRow(),getColumnIndex("id_df")));
            countriesT.deleteRow(getID_DocFacade());
            refreshTable();
        }
        
    }//GEN-LAST:event_jButtonDelActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
// TODO add your handling code here:
        
        if (table.getSelectedRow() != -1) 
        { 
            
            setRow(table.getSelectedRow());
            if(getRow()==0){
                setAtBegining(true);
            }
            if(getRow()==getMaxRow()){
                setAtEnd(true);
            }
            setAllVariables();
            try 
            {
               
            //    dialog = new aeDocumentFacade(this, true,false,userDocFacade,levelDocFacade,priceList,docType);
                dialog.setVisible(true);
                
            } catch(Exception e)
            {
                e.printStackTrace();
            }
        }else{
            
        }
        
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
// TODO add your handling code here:
       setAllVariablesDefault();
//        countriesT.insertRow(getNom(),getCod(),getNames(),getAnID());
        setID_DocFacade(countriesT.getMaxId());
        refreshTable();
         try 
            {
                dialog = new aeDocumentFacade(this, true,true,userDocFacade,levelDocFacade,priceList,docType);;
                dialog.setVisible(true);
                
            } catch(Exception e)
            {
                e.printStackTrace();
            }
        
        
    }//GEN-LAST:event_jButtonNewActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                FrmDocumentFacade frCN =   new FrmDocumentFacade("ttt",1,1,1,1,1);
                fr.add(frCN);
                frCN.setVisible(true);
                fr.setVisible(true);
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonDeleteAll;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonPrnReport;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextAnLevel;
    private javax.swing.JTextField jTextCod;
    private javax.swing.JTextField jTextName;
    // End of variables declaration//GEN-END:variables
 //--------------- My Variables
  // input parametrs
    private int userDocFacade=0;
    private int levelDocFacade = 0;
    private int priceList=1;
    private int docType;
   
//------------------------------------  
   private String nameContragent;
   private String codeContragent;
   private String bulContragent;
   private String danContragent;
   private String addressContragent;
   private String molContragent;
   private String telContragent;
   private String codeObekt;
   private String nameObekt;
   private String telObekt;
   private String addressObekt;
   private String docFacadeNumber;
   private String docFacadeDate;
   private String docFacadeDistributor;
   private String docFacadeDeliver;
   
   private int idDocFacade;
   private int idContragent;
   private int idObect;
   private int idDistributor;
   private int idDeliver;
   private int storageDocFacade;
   
   private int descriptionPaying =0;
   private String payingDate;
   private double allDDSPaing=0;
   private double totalPaying=0;
   private int userLastEdit = userDocFacade;
   private String commenatDocFacade;
   
   private  String nameColumnsDocFacade[] = {"id_df","id_contragent_in","id_contragent_out","id_n_obekt_in","id_n_obekt_out","ls_n_person_deliv","ls_n_person_dist",
                "Номер на документа","Дата на документа","Код на контрагента","Име на контрагента",
                "Адрес на контрагента","Телефон на контрагента","Дан. No на контрагента","МОЛ на контрагента",
                "Код на обекта","Име на обекта","Адрес на обекта","Телефон на обекта","Код на дистрибутор",
                "Код на доставчика"};  
    private  boolean atBegining=false;
    private  boolean atEnd = false;
    private int row;
    private aeDocumentFacade dialog;
    private imakante.com.vcomponents.iFrame myframe;
    private java.sql.Connection conn;
    private  java.sql.ResultSet rs; 
    private documentFacadeDB countriesT;
    private  imakante.com.CustomTableModel model;
    private  imakante.com.CustomTable table; 
    private java.sql.Connection ccc;  // samo za testvaneto
    private  static JFrame fr = new JFrame("test");
    private String User="imakante";  // vremenna promenliva za test
    private String Pass="imakante";  // vremenna promenliva za test
    private String Url = "jdbc:mysql://www.katsarov.net:3307/mida";  // vremenna promenliva za test
 //---------------END My Variables
 //---------------START MyFunction
private void prepareConn() //TEST
    {
      // samo za testovate ------------
      try
         {
          Class.forName("com.mysql.jdbc.Driver");
           
           ccc = DriverManager.getConnection(Url, User, Pass);
           conn = ccc;
          
         }
         catch(Exception e)
         {
             e.printStackTrace();
         }
      
     /*  try
       {
            setConn(myframe.getConn());
       }
       catch(Exception e)
       {
       e.printStackTrace();
       }*/
  }
private void constructGroupDB() //OK 
    {
        try
        {
            
         countriesT = new documentFacadeDB(conn);
        }
        catch(Exception e)
        
        {
            e.printStackTrace();
        }
        System.out.println("ot construct object");
    }
private void initTable() //OK  -- !!ima za dovyr6wane - skrivane na koloni!!
    {
      try
        {
           
            rs = countriesT.getTable();
            model = new imakante.com.CustomTableModel(conn,rs, nameColumnsDocFacade);
            table = new imakante.com.CustomTable(model);
           
        }
       catch(Exception e)
       {
           e.printStackTrace();
       }
       table.requestFocus();
       try
        {
          table.setEditingRow(0);
       } 
        catch(Exception ex) 
        {
        
        }
     /* // dokato se provejdat testovete
       HideColumns(getColumnIndex("id_df"));
       HideColumns(getColumnIndex("id_contragent"));
       HideColumns(getColumnIndex("id_n_obekt"));
       HideColumns(getColumnIndex("ls_n_person_deliv"));
       HideColumns(getColumnIndex("ls_n_person_dist"));*/
  }
    
 public void windowOpened(java.awt.event.WindowEvent e)
  {
    
   }
  public void windowClosing(java.awt.event.WindowEvent e) // colose frame`s windows
   {
        
   }
        
  public void windowClosed(java.awt.event.WindowEvent e)
   {
        
   }
  public void windowIconified(java.awt.event.WindowEvent e)
   {
      
   }
  public void windowDeiconified(java.awt.event.WindowEvent e)
   {
      
   }
  public void windowActivated(java.awt.event.WindowEvent e)
   {
      
   }
  public void windowDeactivated(java.awt.event.WindowEvent e) 
   {
   
   } 
  
  public void setConn(java.sql.Connection con)
  {
      this.conn = con;
  }
  public documentFacadeDB getCountriesT() //OK
     {
        return countriesT;
    }
    
  public void setCountriesT(documentFacadeDB val)//OK
     {
        this.countriesT = val;
    }
    
  public CustomTableModel getModel()//OK
     {
        return model;
    }
    
  public void setModel(CustomTableModel val)//OK
     {
        this.model = val;
    }
    
  public CustomTable getTable()//OK
     {
        return table;
    }
    
  public void setTable(CustomTable val) //OK
     {
        this.table = val;
    }
    
  public iFrame getMyframe()//OK
     {
        return myframe;
    }
    
  public void setMyframe(iFrame val)//OK
     {
        this.myframe = val;
    }
 
   private int  getMaxRow() 
   {
        int i = 0;
        i  = table.getRowCount() - 1;
        return i;
   }
//-------------------------------->
   public void setNamesContragent(String Name) 
    {
        this.nameContragent = Name;
    }
    public String getNamesContragent() 
    {
        return nameContragent;
    }
   public void setCodeContragent(String code) 
    {
        this.codeContragent = code;
    }
    public String getCodeContragent() 
    {
        return codeContragent;
    }
     public void setBulContragent(String bul) 
    {
        this.codeContragent = bul;
    }
    public String getBulContragent() 
    {
        return bulContragent;
    }
    public void setDanContragent(String dan) 
    {
        this.danContragent = dan;
    }
    public String getDanContragent() 
    {
        return danContragent;
    }
    public void setAddressContragent(String addres) 
    {
        this.addressContragent = addres;
    }
    public String getAddressContragent() 
    {
        return addressContragent;
    }
     public void setMOLContragent(String mol) 
    {
        this.molContragent = mol;
    }
    public String getMOLContragent() 
    {
        return molContragent;
    }
    public void setTelContragent(String tel) 
    {
        this.telContragent = tel;
    }
    public String getTelContragent() 
    {
        return telContragent;
    }
    public void setCodeObekt(String code) 
    {
        this.codeObekt = code;
    }
    public String getCodeObekt() 
    {
        return codeObekt;
    }
     public void setNameObekt(String name) 
    {
        this.nameObekt = name;
    }
    public String getNameObekt() 
    {
        return nameObekt;
    }
     public void setTelObekt(String tel) 
    {
        this.telObekt = tel;
    }
    public String getTelObekt() 
    {
        return telObekt;
    }
    public void setAddressObekt(String addres) 
    {
        this.addressObekt = addres;
    }
    public String getAddressObekt() 
    {
        return addressObekt;
    }
     public void setNumberDocFacade(String numberDocFacade) 
    {
        this.docFacadeNumber = numberDocFacade;
    }
    public String getNumberDocFacade() 
    {
        return docFacadeNumber;
    }
    public void setDateDocFacade(String date) 
    {
        this.docFacadeDate = date;
    }
    public String getDateDocFacade() 
    {
        return docFacadeDate;
    }
     public void setDistributorDocFacade(String dist) 
    {
        this.docFacadeDistributor = dist;
    }
    public String getDistributorDocFacade() 
    {
        return docFacadeDistributor ;
    }
     public void setDeliverDocFacade(String deliv) 
    {
        this.docFacadeDeliver = deliv;
    }
    public String getDeliverDocFacade() 
    {
        return docFacadeDeliver;
    }   
   public void setID_DocFacade(int  id) 
    {
        this.idDocFacade = id;
    }
    public int getID_DocFacade() 
    {
        return idDocFacade;
    }
    public void setID_Contragent(int  id) 
    {
        this.idContragent = id;
    }
    public int getID_Contragent() 
    {
        return idContragent;
    }
     public void setID_Obekt(int  id) 
    {
        this.idObect = id;
    }
    public int getID_Obekt() 
    {
        return idObect;
    }   
    public void setID_Distributor(int  id) 
    {
        this.idDistributor = id;
    }
    public int getID_Distributor() 
    {
        return idDistributor;
    }
     public void setID_Deliver(int  id) 
    {
        this.idDeliver = id;
    }
    public int getID_Deliver() 
    {
        return idDeliver;
    }   
   
    
 public void setContragentData(String in[])
 {
     setCodeContragent(in[0]);
     setBulContragent(in[1]);
     setDanContragent(in[2]);
     setNamesContragent(in[3]);
     setAddressContragent(in[4]);
     setMOLContragent(in[5]);
     setTelContragent(in[6]);
     
 }
  public void setObektData(String in[])
 {  
      setCodeObekt(in[0]);
      setTelObekt(in[1]);
      setNameObekt(in[2]);
      setAddressObekt(in[3]);
  }
   
public void setDistributorData(String in)
{
    setDistributorDocFacade(in);
}
public void setDeliverData(String in)
{
    setDeliverDocFacade(in);
}
public void setDescriptipnPay(int  paying)
{
   this.descriptionPaying = paying;
}
public int getDescriptipnPay()
{
   return descriptionPaying;
} 
public void setPayingDate(String date)
{
   this.payingDate = date;
}
public String getPayingDate()
{
   return payingDate;
}
public void setAllDDSPaingDocFacade(double in)
{
   this.allDDSPaing = in;
}
public double getAllDDSPaingDocFacade()
{
   return allDDSPaing;
}
public void setTotalPayingDocFacade(double in)
{
   this.totalPaying = in;
}
public double getTotalPayingDocFacade()
{
   return totalPaying;
}
public void setuserLastEditDocFacade(int in)
{
   this.userLastEdit= in;
}
public int getuserLastEditDocFacade()
{
   return userLastEdit;
}
public void setUserDocFacade(int in)
{
   this.userDocFacade= in;
}
public int getUserDocFacade()
{
   return userDocFacade;
}



public void setCommenatDocFacade(String in)
{
   this.commenatDocFacade= in;
}
public String getCommenatDocFacade()
{
   return commenatDocFacade;
}
   
// <--------------------------------------- 
 public  int getRow()
   {
        return row;
    }
 public  void setRow(int val) //OK
   {
        row = val;
    }
 public  void mTableEnd() //OK
   {
        setRow(getMaxRow());
        try{
           setAllVariables();
            
            table.changeSelection(getRow(),2,false,false); // za predvijvane na selektiraniq red nazad
            
        }
        catch(ArrayIndexOutOfBoundsException aioobe)
        {
            setRow(getRow() - 1);
            System.out.println("problem");
        }
        setAtBegining(false);
        setAtEnd(true);
    }
 public void mOneRowPlus() //OK
   {
      if(getRow() <= getMaxRow())
      {
        if(getRow() < getMaxRow())
        {
          setRow(getRow()+1);
        }
        setAtBegining(false);
        try
        {
            setAllVariables();
            
            table.changeSelection(getRow(),2,false,false); // za predvijvane na selektiraniq red nazad
        }
        catch(ArrayIndexOutOfBoundsException aioobe)
        {
            setRow(getRow() - 1);
            System.out.println("problem");
        }
        if(getRow() == getMaxRow())
        {
                setAtEnd(true);
        }
      }
 }
 public  void mOneRowMinus() //OK
   {
        if(getRow() >= 0){
            if(getRow() > 0){
                setRow(getRow() - 1);}
            setAtEnd(false);
            try
            {
               setAllVariables();
                
                table.changeSelection(getRow(),2,false,false); // za predvijvane na selektiraniq red nazad
            }
            catch(ArrayIndexOutOfBoundsException aioobe)
            {
                setRow(getRow() + 1);
            }
                System.out.println("problem");}
            if(getRow() == 0){
                setAtBegining(true);
            }
        }   
 public void mTableBegining() //OK
   {
      setRow(0);
        try
        {
            setAllVariables();
            
            table.changeSelection(getRow(),2,false,false); // za predvijvane na selektiraniq red nazad
        }
        catch(ArrayIndexOutOfBoundsException aioobe)
        {
            setRow(getRow() - 1);
            System.out.println("problem");
        }
        setAtBegining(true);
        setAtEnd(false);
 }
 protected  void refreshTable() //OK
   {
        jScrollPane1.remove(table);
        rs = countriesT.getTable();
        model = new imakante.com.CustomTableModel(conn, rs, null);
        table = new imakante.com.CustomTable(model);
        jScrollPane1.getViewport().add(table);
        jScrollPane1.repaint();
        
    }
public  boolean isAtBegining()
   {
        return atBegining;
    }
    
public  void setAtBegining(boolean aAtBegining)
   {
        atBegining = aAtBegining;
    }
    
public  boolean isAtEnd()
   {
        return atEnd;
    }
    
public  void setAtEnd(boolean aAtEnd) 
  {
        atEnd = aAtEnd;
    }
 private int getColumnIndex(String in) //test
 {
     int count = table.getColumnCount();
     for(int i=0; i < count; i++)
     {
         if(table.getColumnName(i).equals(in)) return i;
     }
     return 0;
 }
 private void HideColumns(int col)
 {
   int iColumn = col;
// set column width
    table.getColumnModel().getColumn(iColumn).setMaxWidth(0);
    table.getColumnModel().getColumn(iColumn).setMinWidth(0);
    table.getTableHeader().getColumnModel().getColumn(iColumn).setMaxWidth(0);
    table.getTableHeader().getColumnModel().getColumn(iColumn).setMinWidth(0);

 }
private void setAllVariables() // !!!!da se smenat imenata s imena otgovarq6ti na cyrillica 
    {
        setID_DocFacade((Integer) table.getValueAt(getRow(), getColumnIndex("id_df")));
        setID_Contragent((Integer) table.getValueAt(getRow(), getColumnIndex("id_contragent")));
        setID_Obekt((Integer) table.getValueAt(getRow(), getColumnIndex("id_n_obekt")));
        setID_Deliver((Integer) table.getValueAt(getRow(), getColumnIndex("ls_n_person_deliv")));
        setID_Distributor((Integer) table.getValueAt(getRow(), getColumnIndex("ls_n_person_dist")));
           
        int tmp = (Integer) table.getValueAt(getRow(), getColumnIndex("Номер на документа"));
        setNumberDocFacade(String.valueOf(tmp));
        
        setDateDocFacade((String)table.getValueAt(getRow(),getColumnIndex("Дата на документа")));
        
        tmp = (Integer) table.getValueAt(getRow(), getColumnIndex("Код на контрагента"));
        setCodeContragent(String.valueOf(tmp));
        
        setNamesContragent((String)table.getValueAt(getRow(),getColumnIndex("Име на контрагента")));
        
        setAddressContragent((String)table.getValueAt(getRow(),getColumnIndex("Адрес на контрагента")));
        setTelContragent((String)table.getValueAt(getRow(),getColumnIndex("Телефон на контрагента")));
        setBulContragent((String)table.getValueAt(getRow(),getColumnIndex("Булстат на контрагента")));
        
        setDanContragent((String)table.getValueAt(getRow(),getColumnIndex("Дан. No на контрагента")));
        setMOLContragent((String)table.getValueAt(getRow(),getColumnIndex("МОЛ на контрагента"))); 
        
        setCodeObekt((String)table.getValueAt(getRow(),getColumnIndex("Код на обекта"))); 
        setNameObekt((String)table.getValueAt(getRow(),getColumnIndex("Име на обекта"))); 
        setAddressObekt((String)table.getValueAt(getRow(),getColumnIndex("Адрес на обекта"))); 
        setTelObekt((String)table.getValueAt(getRow(),getColumnIndex("Телефон на обекта"))); 
        
        setDistributorDocFacade((String)table.getValueAt(getRow(),getColumnIndex("Код на дистрибутор"))); 
        setDeliverDocFacade((String)table.getValueAt(getRow(),getColumnIndex("Код на доставчика"))); 
    
    }
private void setAllVariablesDefault() // !!!!da se smenat imenata s imena otgovarq6ti na cyrillica 
    {
        setID_DocFacade(0);
        setID_Contragent(0);
        setID_Obekt(0);
        setID_Deliver(0);
        setID_Distributor(0);
           
        
        setNumberDocFacade("");
        setDateDocFacade("");
        setCodeContragent("");
        setNamesContragent("");
        setAddressContragent("");
        setTelContragent("");
        setBulContragent("");
        setDanContragent("");
        setMOLContragent(""); 
        setCodeObekt(""); 
        setNameObekt(""); 
        setAddressObekt(""); 
        setTelObekt(""); 
        setDistributorDocFacade(""); 
        setDeliverDocFacade(""); 
   
    }

/*public void insertRow()
{
    countriesT.insertRow()
}
public void searchRecords()
{
     countriesT.searchRecords()
}
public void updateRow()
{
     countriesT.updateRow()
}
public void deleteRow()
{
     countriesT.deleteRow()
}*/
}// end class
