/*
 * sales_main.java
 *
 * Created on Четвъвтък, 2005, Юни 2, 14:27
 */

package imakante.sales;

import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author  user
 */
public class sales_main extends javax.swing.JFrame {
    
    /** Creates new form sales_main */
    public sales_main() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jDesktopPane1 = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        docMenu = new javax.swing.JMenu();
        docMenu_Prod = new javax.swing.JMenuItem();
        docMenu_Fak = new javax.swing.JMenuItem();
        docMenu_Razp = new javax.swing.JMenuItem();
        docMenu_Nar = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        kasaMenu = new javax.swing.JMenu();
        nomMenu = new javax.swing.JMenu();
        nomMenu_Stoka = new javax.swing.JMenuItem();
        nomMenu_Klienti = new javax.swing.JMenuItem();
        nomMenu_dost = new javax.swing.JMenuItem();
        sprMenu = new javax.swing.JMenu();
        sluMenu = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\u0418\u041c\u0410\u041a\u0410\u041d\u0422\u0415 \u0422\u044a\u0440\u0433\u043e\u0432\u0441\u043a\u0438 \u043c\u043e\u0434\u0443\u043b");
        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.NORTH);

        docMenu.setText("\u0414\u041e\u041a\u0423\u041c\u0415\u041d\u0422\u0418");
        docMenu_Prod.setText("\u041f\u0440\u043e\u0434\u0430\u0436\u0431\u0438");
        docMenu.add(docMenu_Prod);

        docMenu_Fak.setText("\u0424\u0430\u043a\u0442\u0443\u0440\u0438");
        docMenu.add(docMenu_Fak);

        docMenu_Razp.setText("\u0420\u0430\u0437\u043f\u0438\u0441\u043a\u0438");
        docMenu.add(docMenu_Razp);

        docMenu_Nar.setText("Item");
        docMenu.add(docMenu_Nar);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });

        docMenu.add(exitMenuItem);

        menuBar.add(docMenu);

        kasaMenu.setText("\u041a\u0410\u0421\u0410");
        menuBar.add(kasaMenu);

        nomMenu.setText("\u041d\u041e\u041c\u0415\u041d\u041a\u041b\u0410\u0422\u0423\u0420\u0418");
        nomMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomMenuActionPerformed(evt);
            }
        });

        nomMenu_Stoka.setText("\u0421\u0442\u043e\u043a\u0430");
        nomMenu.add(nomMenu_Stoka);

        nomMenu_Klienti.setText("\u041a\u043b\u0438\u0435\u043d\u0442\u0438");
        nomMenu.add(nomMenu_Klienti);

        nomMenu_dost.setText("\u0414\u043e\u0441\u0442\u0430\u0432\u0447\u0438\u0446\u0438");
        nomMenu.add(nomMenu_dost);

        menuBar.add(nomMenu);

        sprMenu.setText("\u0421\u041f\u0420\u0410\u0412\u041a\u0418");
        menuBar.add(sprMenu);

        sluMenu.setText("\u0421\u041b\u0423\u0416\u0415\u0411\u041d\u0418");
        menuBar.add(sluMenu);

        helpMenu.setText("\u041f\u041e\u041c\u041e\u0429");
        contentMenuItem.setText("\u0421\u044a\u0434\u044a\u0440\u0436\u0430\u043d\u0438\u0435");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setText("\u0410\u0432\u0442\u043e\u0440\u0438");
        helpMenu.add(aboutMenuItem);

        jMenuItem1.setText("Item");
        helpMenu.add(jMenuItem1);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void nomMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomMenuActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_nomMenuActionPerformed
    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sales_main().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenu docMenu;
    private javax.swing.JMenuItem docMenu_Fak;
    private javax.swing.JMenuItem docMenu_Nar;
    private javax.swing.JMenuItem docMenu_Prod;
    private javax.swing.JMenuItem docMenu_Razp;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu kasaMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu nomMenu;
    private javax.swing.JMenuItem nomMenu_Klienti;
    private javax.swing.JMenuItem nomMenu_Stoka;
    private javax.swing.JMenuItem nomMenu_dost;
    private javax.swing.JMenu sluMenu;
    private javax.swing.JMenu sprMenu;
    // End of variables declaration//GEN-END:variables
   
    java.sql.Connection dbConn = null;
    public String dbName = null;
    public String dbURL = null;
    public String dbDriver = null;
    public String dbUser = null;
    public String dbPass = null;
    
    public void loadConn(){
        imakante.com.pubFrmConnection fconn = new imakante.com.pubFrmConnection(this);
        fconn.setVisible(true);
    }
    
    public java.sql.Connection makeConn(String dbDriver,String dbURL,String dbUser, String dbPass) throws java.sql.SQLException {
        
        String DBDriver = dbDriver;
        String DBSource = dbURL;
        String DBUserName = dbUser;
        String DBPassword = dbPass;
        System.out.println(dbURL);
        System.out.println(dbUser);
        System.out.println(dbPass);
        
        try{
            Class.forName(DBDriver);
            dbConn = DriverManager.getConnection(DBSource,DBUserName ,DBPassword);
        } catch(ClassNotFoundException e)  {
            System.err.println("Failed to load driver");
            e.printStackTrace();
            System.exit(1);
        } catch(SQLException e){
            System.err.println("Unable to connect");
            e.printStackTrace();
            System.exit(1);
        }
        if (dbConn != null){
            
        } else {
            JOptionPane.showMessageDialog(null,"Възникнал проблем при осъществаване на връзка с базата.","ИМАКАНТЕ",JOptionPane.WARNING_MESSAGE);
        }
        return dbConn;
    }
    public void closeConn() {
        if (dbConn != null ){
            try {
                dbConn.close();
            } catch(SQLException sq2){
            }}
        dbName = null;
        dbURL = null;
        dbDriver = null;
        dbUser = null;
        dbPass = null;
    } 
    
      
    public String setDBDriver(String strDriver){
        dbDriver = strDriver;
        return dbDriver;
    }
    
    
    public String setDBSource(String strSource){
        dbURL = strSource;
        return dbURL;
    }
    
    
    public String setUser(String strUser){
        dbUser = strUser;
        return dbUser;
    }
    public String setFirm(String strFirm){
        
        dbName = strFirm;
        return dbName;
    }
    
    public String setPass(String strPass){
        dbPass = strPass;
        return dbPass;
    }
}
