/*
 * sales_main.java
 *
 * Created on Четвъвтък, 2005, Юни 2, 14:27
 */

package imakante.sales;

import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author  user
 */
public class sales_main extends javax.swing.JFrame {
    
    /** Creates new form sales_main */
    public sales_main() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        docMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        касаMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        docMenu.setText("\u0414\u041e\u041a\u0423\u041c\u0415\u041d\u0422\u0418");
        openMenuItem.setText("Open");
        docMenu.add(openMenuItem);

        saveMenuItem.setText("Save");
        docMenu.add(saveMenuItem);

        saveAsMenuItem.setText("Save As ...");
        docMenu.add(saveAsMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });

        docMenu.add(exitMenuItem);

        menuBar.add(docMenu);

        касаMenu.setText("\u041a\u0410\u0421\u0410");
        cutMenuItem.setText("Cut");
        касаMenu.add(cutMenuItem);

        copyMenuItem.setText("Copy");
        касаMenu.add(copyMenuItem);

        pasteMenuItem.setText("Paste");
        касаMenu.add(pasteMenuItem);

        deleteMenuItem.setText("Delete");
        касаMenu.add(deleteMenuItem);

        menuBar.add(касаMenu);

        helpMenu.setText("\u041f\u041e\u041c\u041e\u0429");
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        jMenuItem1.setText("Item");
        helpMenu.add(jMenuItem1);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sales_main().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu docMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenu касаMenu;
    // End of variables declaration//GEN-END:variables
   java.sql.Connection dbConn = null;
    public String dbName = null;
    public String dbURL = null;
    public String dbDriver = null;
    public String dbUser = null;
    public String dbPass = null;
    public void loadConn(){
        imakante.com.pubFrmConnection fconn = new imakante.com.pubFrmConnection(this);
        fconn.setVisible(true);
    }
    
    public java.sql.Connection makeConn(String dbDriver,String dbURL,String dbUser, String dbPass) throws java.sql.SQLException {
        
        String DBDriver = dbDriver;
        String DBSource = dbURL;
        String DBUserName = dbUser;
        String DBPassword = dbPass;
        System.out.println(dbURL);
        System.out.println(dbUser);
        System.out.println(dbPass);
        
        try{
            Class.forName(DBDriver);
            dbConn = DriverManager.getConnection(DBSource,DBUserName ,DBPassword);
        } catch(ClassNotFoundException e)  {
            System.err.println("Failed to load driver");
            e.printStackTrace();
            System.exit(1);
        } catch(SQLException e){
            System.err.println("Unable to connect");
            e.printStackTrace();
            System.exit(1);
        }
        if (dbConn != null){
            
        } else {
            JOptionPane.showMessageDialog(null,"Възникнал проблем при осъществаване на връзка с базата.","ИМАКАНТЕ",JOptionPane.WARNING_MESSAGE);
        }
        return dbConn;
    }
    public void closeConn() {
        if (dbConn != null ){
            try {
                dbConn.close();
            } catch(SQLException sq2){
            }}
        dbName = null;
        dbURL = null;
        dbDriver = null;
        dbUser = null;
        dbPass = null;
    } 
    
      
    public String setDBDriver(String strDriver){
        dbDriver = strDriver;
        return dbDriver;
    }
    
    
    public String setDBSource(String strSource){
        dbURL = strSource;
        return dbURL;
    }
    
    
    public String setUser(String strUser){
        dbUser = strUser;
        return dbUser;
    }
    public String setFirm(String strFirm){
        
        dbName = strFirm;
        return dbName;
    }
    
    public String setPass(String strPass){
        dbPass = strPass;
        return dbPass;
    }
}
