INSERT INTO rep_product
  (id_pc, id_pm, parcel_pc, dateofexpire_pc, barcod_pc, id_pp, id_ppp, id_pf, exp_list_pc, id_pd, id_n_group, name_pm, fname_pm, sname_pm, cname_pm, cod1_pm, cod2_pm, barcod_pm, max_pop_pm, expertsheet_pm, flag_pm, min_pm, code_pm, id_sl_curs, price1_pp, price2_pp, price3_pp, price0_pp)
VALUES
  (1, 3, 1, "1.11.2006", 0, 0, 0, 0, "", 1, 15, "БОЛЯРКА БОКС 4", "БОЛЯРКА БОКС 4", "БОЛЯРКА БО", "БОЛЯРКА БО", "", "", "2121211", 0, "12221", 0, 1, 1, 1, "0,12", "0,145", "0,152", "0,11");

