

package nom;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.*;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.DefaultTableCellRenderer;
import java.util.Date;
public class aeConsigment extends imakante.com.vcomponents.iDialog {
    
    /** Creates new form aeProduct */
    public aeConsigment(imakante.com.vcomponents.iInternalFrame frame, boolean modal, boolean isnew)// Test
    {
        super(frame, modal);
        this.myframe = frame;
        this.isNew = isnew; // opredelq dali zapisa sy6testwuwa v bazata;
        this.myParent = (nom.FrmProduct) frame;
        initComponents();
        
        getNavigatiionState();
        java.awt.Dimension dim = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        int x = (((dim.width)-(this.getSize().width))/2);
        int y = (((dim.height)-(this.getSize().height))/2);
        this.setLocation(x, y);
        
         // ------------Popylvane na colonite za opisanie
        splitNameOfColumn1 = myParent.getCountriesT().getProductDescriptionColumn();
        
        for(int i=0;i<splitNameOfColumn1.length;i++) {
            
            jComboBoxDescript1.addItem(new String(splitNameOfColumn1[i]));
            jComboBoxDescript2.addItem(new String(splitNameOfColumn1[i]));
            jComboBoxDescript3.addItem(new String(splitNameOfColumn1[i]));
            
        }
       
        setInputLisener();
        repaintComp();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelWeb = new javax.swing.JLabel();
        jLabelMOL = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jTextFieldFee = new javax.swing.JTextField();
        jTextFieldPromoPrices = new javax.swing.JTextField();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxPartida = new javax.swing.JComboBox();
        jTextFieldBarCod = new javax.swing.JTextField();
        jLabelNM = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanelInfoProdukt = new javax.swing.JPanel();
        jTextFieldCode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonToBegin = new javax.swing.JButton();
        jButtonOneRowM = new javax.swing.JButton();
        jButtonOneRowP = new javax.swing.JButton();
        jButtonToEnd = new javax.swing.JButton();
        jPanelDescription = new javax.swing.JPanel();
        jComboBoxDescript1 = new javax.swing.JComboBox();
        jComboBoxDescript2 = new javax.swing.JComboBox();
        jComboBoxDescript3 = new javax.swing.JComboBox();
        jTextFieldDescript1 = new javax.swing.JTextField();
        jTextFieldDescript2 = new javax.swing.JTextField();
        jTextFieldDescript3 = new javax.swing.JTextField();
        jTextFieldExpertList = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 270));
        jLabelEmail.setText("\u0426\u0435\u043d\u0430:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 5);
        jPanel1.add(jLabelEmail, gridBagConstraints);

        jLabelWeb.setText("\u0422\u0430\u043a\u0441\u0438:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabelWeb, gridBagConstraints);

        jLabelMOL.setText("\u041f\u0440\u043e\u043c\u043e. \u0446\u0435\u043d\u0438:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 10, 5);
        jPanel1.add(jLabelMOL, gridBagConstraints);

        jTextFieldPrice.setEditable(false);
        jTextFieldPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldPrice.setMinimumSize(new java.awt.Dimension(170, 20));
        jTextFieldPrice.setPreferredSize(new java.awt.Dimension(170, 20));
        jTextFieldPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPriceFocusLost(evt);
            }
        });
        jTextFieldPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPriceKeyPressed(evt);
            }
        });
        jTextFieldPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldPriceMousePressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFieldPrice, gridBagConstraints);

        jTextFieldFee.setEditable(false);
        jTextFieldFee.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldFee.setMinimumSize(new java.awt.Dimension(170, 20));
        jTextFieldFee.setPreferredSize(new java.awt.Dimension(170, 20));
        jTextFieldFee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFeeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldFeeFocusLost(evt);
            }
        });
        jTextFieldFee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFeeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFeeKeyReleased(evt);
            }
        });
        jTextFieldFee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldFeeMousePressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 20);
        jPanel1.add(jTextFieldFee, gridBagConstraints);

        jTextFieldPromoPrices.setEditable(false);
        jTextFieldPromoPrices.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldPromoPrices.setMinimumSize(new java.awt.Dimension(170, 20));
        jTextFieldPromoPrices.setPreferredSize(new java.awt.Dimension(170, 20));
        jTextFieldPromoPrices.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPromoPricesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPromoPricesFocusLost(evt);
            }
        });
        jTextFieldPromoPrices.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPromoPricesKeyPressed(evt);
            }
        });
        jTextFieldPromoPrices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldPromoPricesMousePressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFieldPromoPrices, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 20);
        jPanel1.add(jXDatePicker1, gridBagConstraints);

        jLabel1.setText("\u0414\u0430\u0442\u0430:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("\u041f\u0430\u0440\u0442\u0438\u0434\u0430 \u2116:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel2, gridBagConstraints);

        jComboBoxPartida.setEditable(true);
        jComboBoxPartida.setPreferredSize(new java.awt.Dimension(170, 20));
        jComboBoxPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPartidaActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 20);
        jPanel1.add(jComboBoxPartida, gridBagConstraints);

        jTextFieldBarCod.setText("0000000000");
        jTextFieldBarCod.setPreferredSize(new java.awt.Dimension(170, 20));
        jTextFieldBarCod.setInputVerifier(new imakante.com.InputIntegerVerifier(10));
        jTextFieldBarCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBarCodKeyPressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 20);
        jPanel1.add(jTextFieldBarCod, gridBagConstraints);

        jLabelNM.setText("\u0411\u0430\u0440\u043a\u043e\u0434:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabelNM, gridBagConstraints);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 600, 140));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(650, 40));
        jButton1.setText("\u0421\u044a\u0445\u0440\u0430\u043d\u0438");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton1);

        jButton3.setText("\u0417\u0430\u0442\u0432\u043e\u0440\u0438");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton3);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 600, 37));

        jPanelInfoProdukt.setLayout(new java.awt.GridBagLayout());

        jPanelInfoProdukt.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u0437\u0430 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanelInfoProdukt.setPreferredSize(new java.awt.Dimension(700, 100));
        jTextFieldCode.setEditable(false);
        jTextFieldCode.setOpaque(false);
        jTextFieldCode.setPreferredSize(new java.awt.Dimension(170, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 159;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 10);
        jPanelInfoProdukt.add(jTextFieldCode, gridBagConstraints);

        jLabel4.setText("\u041a\u043e\u0434:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 5);
        jPanelInfoProdukt.add(jLabel4, gridBagConstraints);

        jTextFieldName.setBackground(new java.awt.Color(235, 235, 200));
        jTextFieldName.setEditable(false);
        jTextFieldName.setOpaque(false);
        jTextFieldName.setPreferredSize(new java.awt.Dimension(170, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 159;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 10);
        jPanelInfoProdukt.add(jTextFieldName, gridBagConstraints);

        jLabelName.setText("\u0418\u043c\u0435:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanelInfoProdukt.add(jLabelName, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("\u041d\u0430\u0432\u0438\u0433\u0430\u0446\u0438\u044f"));
        jPanel3.setPreferredSize(new java.awt.Dimension(230, 80));
        jButtonToBegin.setText("<<");
        jButtonToBegin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToBeginActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonToBegin);

        jButtonOneRowM.setText("<");
        jButtonOneRowM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOneRowMActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonOneRowM);

        jButtonOneRowP.setText(">");
        jButtonOneRowP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOneRowPActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonOneRowP);

        jButtonToEnd.setText(">>");
        jButtonToEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToEndActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonToEnd);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelInfoProdukt.add(jPanel3, gridBagConstraints);

        jPanelDescription.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "\u0420\u0430\u0437\u0444\u0430\u0441\u043e\u0432\u043a\u0430", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanelDescription.setMinimumSize(new java.awt.Dimension(250, 60));
        jPanelDescription.setPreferredSize(new java.awt.Dimension(300, 80));
        jComboBoxDescript1.setEnabled(false);
        jComboBoxDescript1.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanelDescription.add(jComboBoxDescript1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 18));

        jComboBoxDescript2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jComboBoxDescript2.setEnabled(false);
        jComboBoxDescript2.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanelDescription.add(jComboBoxDescript2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 70, 18));

        jComboBoxDescript3.setEnabled(false);
        jComboBoxDescript3.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanelDescription.add(jComboBoxDescript3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 70, 18));

        jTextFieldDescript1.setEditable(false);
        jTextFieldDescript1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDescript1.setText("1");
        jTextFieldDescript1.setAutoscrolls(false);
        jTextFieldDescript1.setOpaque(false);
        jTextFieldDescript1.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanelDescription.add(jTextFieldDescript1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, 19));

        jTextFieldDescript2.setBackground(new java.awt.Color(235, 235, 200));
        jTextFieldDescript2.setEditable(false);
        jTextFieldDescript2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDescript2.setAutoscrolls(false);
        jTextFieldDescript2.setOpaque(false);
        jTextFieldDescript2.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanelDescription.add(jTextFieldDescript2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 70, 19));

        jTextFieldDescript3.setEditable(false);
        jTextFieldDescript3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDescript3.setAutoscrolls(false);
        jTextFieldDescript3.setOpaque(false);
        jTextFieldDescript3.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanelDescription.add(jTextFieldDescript3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 70, 19));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelInfoProdukt.add(jPanelDescription, gridBagConstraints);

        jTextFieldExpertList.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextFieldExpertList.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 20);
        jPanelInfoProdukt.add(jTextFieldExpertList, gridBagConstraints);

        jLabel3.setText("\u0415\u043a\u0441\u043f\u0435\u0440\u0442\u0435\u043d \u043b\u0438\u0441\u0442:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 5);
        jPanelInfoProdukt.add(jLabel3, gridBagConstraints);

        getContentPane().add(jPanelInfoProdukt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPartidaActionPerformed
// TODO add your handling code here:
       
        if(!isNew)
        {
            ctest++;
            repaintComp();
            
        }
        System.out.println("ddddddddddddddddd " + ctest);
    }//GEN-LAST:event_jComboBoxPartidaActionPerformed
    
    private void jTextFieldFeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFeeKeyPressed
// TODO add your handling code here:
        try {
            prodictPriceFee =  new aeProductPriceFee(null,true,id_pf,false);
            prodictPriceFee.setVisible(true);
            
        } catch(Exception e) {
            e.printStackTrace();
        }
        repaintComp();
    }//GEN-LAST:event_jTextFieldFeeKeyPressed
                    
    private void jTextFieldFeeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFeeFocusGained
// TODO add your handling code here:
        jTextFieldFee.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
    }//GEN-LAST:event_jTextFieldFeeFocusGained
    
    private void jTextFieldFeeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFeeFocusLost
// TODO add your handling code here:
        jTextFieldFee.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_jTextFieldFeeFocusLost
    
    private void jTextFieldFeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFeeKeyReleased
// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFeeKeyReleased
    
    private void jTextFieldFeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldFeeMousePressed
// TODO add your handling code here:
        try {
            prodictPriceFee =  new aeProductPriceFee(myParent,true,id_pf,false);
            prodictPriceFee.setVisible(true);
            
            
        } catch(Exception e) {
            e.printStackTrace();
        }
     //   repaintComp();
    }//GEN-LAST:event_jTextFieldFeeMousePressed
    
    private void jTextFieldPromoPricesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPromoPricesFocusLost
// TODO add your handling code here:
        jTextFieldPromoPrices.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_jTextFieldPromoPricesFocusLost
    
    private void jTextFieldPromoPricesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPromoPricesFocusGained
// TODO add your handling code here:
        jTextFieldPromoPrices.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
    }//GEN-LAST:event_jTextFieldPromoPricesFocusGained
    
    private void jTextFieldPromoPricesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPromoPricesMousePressed
// TODO add your handling code here:
        try {
            promoDialog = new aeProductPricePromotion(myParent,true,id_ppp,false);
            promoDialog.setVisible(true);
            
            
        } catch(Exception e) {
            e.printStackTrace();
        }
     //   repaintComp();
    }//GEN-LAST:event_jTextFieldPromoPricesMousePressed
    
    private void jTextFieldPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPriceFocusLost
// TODO add your handling code here:
        jTextFieldPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_jTextFieldPriceFocusLost
    
    private void jTextFieldPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPriceFocusGained
// TODO add your handling code here:
        jTextFieldPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
    }//GEN-LAST:event_jTextFieldPriceFocusGained
    
    private void jTextFieldPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPriceKeyPressed
// TODO add your handling code here:
        
        
        try {
           
              porductPrice =  new nom.aeProductPrice(myParent,true,id_pp,false);
              porductPrice.setVisible(true);
            
            
        } catch(Exception e) {
            e.printStackTrace();
        }
        
        repaintComp();
    }//GEN-LAST:event_jTextFieldPriceKeyPressed
    
    private void jTextFieldPriceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPriceMousePressed
// TODO add your handling code here:
        try {
           porductPrice =  new nom.aeProductPrice(myParent,true,id_pp,false);
           porductPrice.setVisible(true);
            
            
        } catch(Exception e) {
            e.printStackTrace();
        }
       // repaintComp();
    }//GEN-LAST:event_jTextFieldPriceMousePressed
    
    //
    private void jButtonToEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToEndActionPerformed
// TODO add your handling code here:
        isNew = false;
        isFirstTimeAppearce = true;
        myParent.mTableEnd();
        jButtonToEnd.setEnabled(false);
        jButtonOneRowP.setEnabled(false);
        jButtonToEnd.repaint();
        jButtonOneRowP.repaint();
        
        
        jButtonToBegin.setEnabled(true);
        jButtonOneRowM.setEnabled(true);
        jButtonToBegin.repaint();
        jButtonOneRowM.repaint();
        
        System.out.println(String.valueOf(myParent.getId_Group()));
        repaintComp();
    }//GEN-LAST:event_jButtonToEndActionPerformed
    
    private void jButtonOneRowPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOneRowPActionPerformed
// TODO add your handling code here:
        isNew = false;
        isFirstTimeAppearce = true;
        myParent.mOneRowPlus();
        if(myParent.isAtEnd()) {
            jButtonToEnd.setEnabled(false);
            jButtonOneRowP.setEnabled(false);
            jButtonToEnd.repaint();
            jButtonOneRowP.repaint();
            
        }
        
        jButtonToBegin.setEnabled(true);
        jButtonOneRowM.setEnabled(true);
        jButtonToBegin.repaint();
        jButtonOneRowM.repaint();
        System.out.println(String.valueOf(myParent.getId_Group()));
        repaintComp();
    }//GEN-LAST:event_jButtonOneRowPActionPerformed
    
    private void jButtonOneRowMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOneRowMActionPerformed
// TODO add your handling code here:
        isNew = false;
        isFirstTimeAppearce = true;
        myParent.mOneRowMinus();
        if(myParent.isAtBegining()) {
            jButtonToBegin.setEnabled(false);
            jButtonOneRowM.setEnabled(false);
            jButtonToBegin.repaint();
            jButtonOneRowM.repaint();
            
        }
        jButtonToEnd.setEnabled(true);
        jButtonOneRowP.setEnabled(true);
        jButtonToEnd.repaint();
        jButtonOneRowP.repaint();
        System.out.println(String.valueOf(myParent.getId_Group()));
        repaintComp();
    }//GEN-LAST:event_jButtonOneRowMActionPerformed
    
    private void jButtonToBeginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToBeginActionPerformed
// TODO add your handling code here:
        isNew = false;
        isFirstTimeAppearce = true;
        myParent.mTableBegining();
        
        jButtonToBegin.setEnabled(false);
        jButtonOneRowM.setEnabled(false);
        jButtonToBegin.repaint();
        jButtonOneRowM.repaint();
        
        jButtonToEnd.setEnabled(true);
        jButtonOneRowP.setEnabled(true);
        jButtonToEnd.repaint();
        jButtonOneRowP.repaint();
        System.out.println(String.valueOf(myParent.getId_Group()));
        repaintComp();
    }//GEN-LAST:event_jButtonToBeginActionPerformed
    
    private void jTextFieldPromoPricesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPromoPricesKeyPressed
// TODO add your handling code here:
        try {
            new aeProductPricePromotion(myParent,true,id_ppp,false).setVisible(true);
            
            
        } catch(Exception e) {
            e.printStackTrace();
        }
        
        repaintComp();
    }//GEN-LAST:event_jTextFieldPromoPricesKeyPressed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
        if(isNew)
        {
         Iterator it = splitPartidaNomer.iterator();
         nom.infoConsigment partidi;
         partidi = (infoConsigment)it.next();
         myParent.getCountriesT().deleteConsigment(partidi.getId_PC());
        }
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
      if(isNew)  
      {
          try
          {
          String str = (String)jComboBoxPartida.getItemAt(0);
          if(str.equals("--------------"))
          {
              return;
          }
          }
          catch(Exception e){}
                  
      }
      String strDate;
      int partidaNomer = (Integer)jComboBoxPartida.getSelectedItem();
      imakante.com.dateManipulation newDate = new imakante.com.dateManipulation();
      strDate = String.valueOf(jXDatePicker1.getDate().getDate());
      strDate += "/" + String.valueOf(jXDatePicker1.getDate().getMonth()+1);
      strDate += "/" + String.valueOf(jXDatePicker1.getDate().getYear()+1900);
      System.out.println(strDate)  ;
      String expireDate = newDate.convertDate(strDate);
      System.out.println(expireDate)  ;
      int barcod = Integer.parseInt(jTextFieldBarCod.getText());
      int id_pc = 0;
      int selItem = jComboBoxPartida.getSelectedIndex();
      String exp_list = jTextFieldExpertList.getText();
      Iterator it = splitPartidaNomer.iterator();
      nom.infoConsigment partidi;
           
           while(it.hasNext())
           {
              partidi = (nom.infoConsigment) it.next();
              if(partidi.getConnection()==selItem)
              {
                 id_pc = partidi.getId_PC();
                 partidi.setBarCod(barcod);
                 break;
              }
             
              
             
           }
      
          if(myParent.isTypedFee | myParent.isTypedPrice | myParent.isTypedPromoPrice)
          {
             if(myParent.isTypedFee)  id_pf = myParent.saveProductFeeToDB();
             if(myParent.isTypedPrice)  id_pp = myParent.saveNewPriceToDb();          
             if(myParent.isTypedPromoPrice)  id_ppp = myParent.saveProductPromotionPriceToDB();
         }
       myParent.getCountriesT().updateConsigment(id_pc,id_pp,id_ppp,id_pf,id_pm,partidaNomer,expireDate,barcod,exp_list);
       isNew = false;
        //  jButton3.doClick(); // zatvarq se aeProsuct
     //   repaintComp();
    
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jTextFieldBarCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBarCodKeyPressed
// TODO add your handling code here:
        // pri natiskane na F7 6te se izvikva aContragent, za izbor na naseleno mqsto ot bazata danni
        
    }//GEN-LAST:event_jTextFieldBarCodKeyPressed
    
    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aeProduct(new JFrame(),true,true,1).setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonOneRowM;
    private javax.swing.JButton jButtonOneRowP;
    private javax.swing.JButton jButtonToBegin;
    private javax.swing.JButton jButtonToEnd;
    private javax.swing.JComboBox jComboBoxDescript1;
    private javax.swing.JComboBox jComboBoxDescript2;
    private javax.swing.JComboBox jComboBoxDescript3;
    private javax.swing.JComboBox jComboBoxPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelMOL;
    private javax.swing.JLabel jLabelNM;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelWeb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDescription;
    private javax.swing.JPanel jPanelInfoProdukt;
    private javax.swing.JTextField jTextFieldBarCod;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldDescript1;
    private javax.swing.JTextField jTextFieldDescript2;
    private javax.swing.JTextField jTextFieldDescript3;
    private javax.swing.JTextField jTextFieldExpertList;
    private javax.swing.JTextField jTextFieldFee;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldPromoPrices;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables
    //--------------- My Variables
    private FrmProduct myParent;
    private javax.swing.JComboBox jComboBoxColumn1 = new javax.swing.JComboBox();
    private javax.swing.JComboBox jComboBoxColumn2 = new javax.swing.JComboBox();
    private javax.swing.JComboBox jComboBoxColumn3 = new javax.swing.JComboBox();
    
    private imakante.com.vcomponents.iInternalFrame myframe;
    private String splitNameOfColumn1[] = null;
    private String splitNameOfColumn2[] = null;
    private String splitNameOfColumn3[] = null;
    private aeProductPricePromotion promoDialog;
    private aeProductPrice          porductPrice;
    private aeProductPriceFee       prodictPriceFee;
    private boolean  isNewInputContragent = true;
    private boolean isEarseString = false;
    boolean isNew; // za opredelqne dali zapisa e 4isto nov, t.e dali ne sy6testva b bazata
    private int id_pm,id_pp,id_ppp,id_pf;
    private infoConsigment infoPartida;
    private ArrayList splitPartidaNomer;
    private boolean isFirstTimeAppearce = true;
    private int ctest = 0;
//---------------END My Variables
//---------------START MyFunction
    private void getNavigatiionState() // ok
    {
        if(myParent.isAtBegining()) {
            jButtonToBegin.setEnabled(false);
            jButtonOneRowM.setEnabled(false);
            jButtonToBegin.repaint();
            jButtonOneRowM.repaint();
        }
        if(myParent.isAtEnd()) {
            jButtonToEnd.setEnabled(false);
            jButtonOneRowP.setEnabled(false);
            jButtonToEnd.repaint();
            jButtonOneRowP.repaint();
        }
    }
    private void repaintComp() // Test
    {
       
       id_pm =  myParent.getId_PM();
       jTextFieldName.setText(myParent.getNamePM());
     
       jTextFieldCode.setText(myParent.getCodePM());
       if((myParent.getId_PD()!=0)) // n_product_description
        {
            String description[][] = myParent.getCountriesT().getDescription(myParent.getId_PD());
            int newItem = getNewComboBoxColumnIndex(Integer.parseInt(description[0][0]));
            jComboBoxDescript1.setSelectedIndex(newItem);
            newItem = getNewComboBoxColumnIndex(Integer.parseInt(description[1][0]));
            jComboBoxDescript2.setSelectedIndex(newItem);
            newItem = getNewComboBoxColumnIndex(Integer.parseInt(description[2][0]));
            jComboBoxDescript3.setSelectedIndex(newItem);
         // jTextFieldDescript1.setText(description[0][1]);
            jTextFieldDescript2.setText(description[1][1]);
            jTextFieldDescript3.setText(description[2][1]);
         
        }
        if(myParent.getId_PF()!=0)
        {
            id_pf = myParent.getId_PF();
            String  fee[] = myParent.getCountriesT().getProdictFee(myParent.getId_PF());
            jTextFieldFee.setText(fee[0]);
        }
        else jTextFieldFee.setText(myParent.getViewFee());
        if (myParent.getId_PP()!=0) 
        {
           id_pp = myParent.getId_PP();
            String price[] = myParent.getCountriesT().getProductPrice(myParent.getId_PP());
            jTextFieldPrice.setText(price[0]);
        }
        else jTextFieldPrice.setText(myParent.getViewPrice());
        if (myParent.getId_PPP()!=0) 
        {
           id_ppp = myParent.getId_PPP();
            String promotion_price[] = myParent.getCountriesT().getProductPromotionPrice(myParent.getId_PPP());
            jTextFieldPromoPrices.setText(promotion_price[0]);
        }
        else jTextFieldPromoPrices.setText(myParent.getViewPromoPrice());
       
       
       
       
//------------------------------      
        if(isNew)
        {
           int id_pc =  myParent.getCountriesT().insertConsigment(0,0,0,0,0,"2000-01-01",0,"");
           jComboBoxPartida.removeAllItems();
           jComboBoxPartida.addItem(new String("--------------")) ; // za noviq produkt
          
           splitPartidaNomer = myParent.getCountriesT().getConsigmentFromIdPM(id_pm);
           Iterator it = splitPartidaNomer.iterator();
           nom.infoConsigment partidi;
           
           while(it.hasNext())
           {
              partidi = (nom.infoConsigment) it.next();
              if(partidi.getConnection()==0)
              {
                 partidi.setId_PC(id_pc);
              }
              else
              {
                 jComboBoxPartida.addItem(new Integer(partidi.getPartidaNomer())); 
                 
              }
              
             
           }
       
           jComboBoxPartida.grabFocus();
           jComboBoxPartida.getEditor().selectAll();
           
            
        }
        else  
        {
          int id_pc =0;
          int  dateInt[]= new int[3]; 
          if(isFirstTimeAppearce)
          {
          isFirstTimeAppearce = false;
          jComboBoxPartida.removeAllItems();
          splitPartidaNomer = myParent.getCountriesT().getConsigmentFromIdPM(id_pm);
          splitPartidaNomer.remove(0);
          Iterator it = splitPartidaNomer.iterator();
          nom.infoConsigment partidi;
         
           while(it.hasNext())
           {
              partidi = (nom.infoConsigment) it.next();
              jComboBoxPartida.addItem(new Integer(partidi.getPartidaNomer())); 
              partidi.setConnection(partidi.getConnection()-1);
              if(partidi.getConnection()==0)
              {
                  jComboBoxPartida.setSelectedIndex(0);
                  dateInt = partidi.getExpireDateAsInt();
                  id_pc = partidi.getId_PC();
                  jTextFieldBarCod.setText(String.valueOf(partidi.getBarCod()));
                  jTextFieldExpertList.setText(String.valueOf(partidi.getExpertList()));
              };
           }
          System.out.println("ffffff---fffffffffff--ff  " + ctest);
          
          }
          else
          {
           int selIndex = jComboBoxPartida.getSelectedIndex();
           Iterator it = splitPartidaNomer.iterator();
           nom.infoConsigment partidi;
         
           while(it.hasNext())
           {
             partidi = (nom.infoConsigment) it.next();
             if(partidi.getConnection()==selIndex)
             {
                 id_pc = partidi.getId_PC();
                 dateInt = partidi.getExpireDateAsInt();
                 jTextFieldBarCod.setText(String.valueOf(partidi.getBarCod()));
                 jTextFieldExpertList.setText(String.valueOf(partidi.getExpertList()));
             }
           }
           
          }
          
          System.out.println("id_pc : "+ id_pc);
          Date date = new Date(dateInt[2]-1900,dateInt[1]-1,dateInt[0]);
          jXDatePicker1.setDate(date);

          int pricePartida[] = myParent.getCountriesT().getPriceIDs(id_pc);
          System.out.println("pricePartida[0] " + pricePartida[0] );
           System.out.println("pricePartida[1] " + pricePartida[1] );
            System.out.println("pricePartida[2] " + pricePartida[2] );
          if(pricePartida[0]!=0)
          {
              id_pp =pricePartida[0];
              id_ppp =pricePartida[1];
              id_pf =pricePartida[2];
              String  fee[] = myParent.getCountriesT().getProdictFee(id_pf);
              jTextFieldFee.setText(fee[0]);
              String price[] = myParent.getCountriesT().getProductPrice(id_pp);
              jTextFieldPrice.setText(price[0]);
              String promotion_price[] = myParent.getCountriesT().getProductPromotionPrice(id_ppp);
              jTextFieldPromoPrices.setText(promotion_price[0]);
              System.out.println("id_pp " + id_pp);
              System.out.println("fee " + fee[0]);
              System.out.println("id_ppp " + id_ppp);
              System.out.println("price " + price[0]);
              System.out.println("id_pf " + id_pf);
              System.out.println("promotion_price " + promotion_price[0]);
              
              
              
          }
           
        }
  
    }
   
   
    private boolean  setAllVariables()
    {
        boolean isOk= true;
        
       
        return isOk;
    }
    
    private void showMessage() {
        JOptionPane.showMessageDialog(this,"\u041c\u043e\u043b\u044f, \u0432\u044a\u0432\u0435\u0434\u0435\u0442\u0435 \u043a\u043e\u0440\u0435\u043a\u043d\u043e \u0434\u0430\u043d\u043d\u0438\u0442\u0435");
        
        
    }
   private int getNewComboBoxIndex(int oldindex) //OK
    {
        int newindex= 0;
        for(int i = 0; i < myParent.getCountriesT().getIndexConnOfId().length; i++) {
            if(myParent.getCountriesT().getIndexConnOfId()[i]==oldindex) {
                newindex = i;
                break;
            }
        }
        return newindex;
    }
    
    private int getNewComboBoxColumnIndex(int oldindex) //OK
    {
        int newindex= 0;
        for(int i = 0; i < myParent.getCountriesT().getIndexConnOfIdColumn().length; i++) {
            if(myParent.getCountriesT().getIndexConnOfIdColumn()[i]==oldindex) {
                newindex = i;
                break;
            }
        }
        return newindex;
    }  
  private void setInputLisener()
  {
      jComboBoxPartida.getEditor().addActionListener(new ActionListener() {
          public void actionPerformed(ActionEvent e)
          {
             Object ob = jComboBoxPartida.getEditor().getItem();
            
             if(!isEarseString)
             {
                if(isNew) 
                {
                    jComboBoxPartida.removeItem((String)"--------------");
                    jComboBoxPartida.insertItemAt(new Integer(Integer.parseInt((String)ob)),0);
                }
                else
                {
                  jComboBoxPartida.insertItemAt(new Integer((Integer)ob),0);
                  jComboBoxPartida.removeItemAt(jComboBoxPartida.getSelectedIndex()); 
                }
                 
             }
             else 
             {
                 jComboBoxPartida.insertItemAt(new Integer((Integer)ob),0);
                 jComboBoxPartida.removeItemAt(jComboBoxPartida.getSelectedIndex());
             }
            
             
             isEarseString = true;
            
             
             jComboBoxPartida.setSelectedIndex(0);
             jButton1.grabFocus();
          }
      });
  }
}// end class

