
package nom;

import imakante.com.vcomponents.iInternalFrame;
import javax.swing.JOptionPane;
public class aeProductPriceFee extends imakante.com.vcomponents.iDialog 
{
    
    /** Creates new form aeProductPriceFee */
    public aeProductPriceFee(imakante.com.vcomponents.iInternalFrame frame, boolean modal,int id_price, boolean isnew)
    {
        
        super(frame, modal);
        this.myParent =(FrmProduct) frame;
        this.id_price = id_price;
        this.isNew = isnew;
        initComponents();
        if(!isNew) getDataByID();
        this.setResizable(false);
        java.awt.Dimension dim = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        int x = (((dim.width)-(this.getSize().width))/2);
        int y = (((dim.height)-(this.getSize().height))/2);
        this.setLocation(x, y);
        
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDDS = new javax.swing.JTextField();
        jTextFieldAkcizi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldOther = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 33));
        jButtonSave.setText("\u0421\u044a\u0445\u0440\u0430\u043d\u0438");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonSave);

        jButtonClose.setText("\u0417\u0430\u0442\u0432\u043e\u0440\u0438");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonClose);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(320, 200));
        jLabel1.setText("\u0414\u0414\u0421:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 5, 5);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setText("\u0410\u043a\u0446\u0438\u0437\u0438:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 5);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setText("\u0414\u0440\u0443\u0433\u0438:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 5);
        jPanel2.add(jLabel3, gridBagConstraints);

        jTextFieldDDS.setPreferredSize(new java.awt.Dimension(80, 20));
        jTextFieldDDS.setInputVerifier(new imakante.com.InputDoubleVerifier());
        jTextFieldDDS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDDSKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDDSKeyReleased(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 20);
        jPanel2.add(jTextFieldDDS, gridBagConstraints);

        jTextFieldAkcizi.setPreferredSize(new java.awt.Dimension(80, 20));
        jTextFieldAkcizi.setInputVerifier(new imakante.com.InputDoubleVerifier());
        jTextFieldAkcizi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAkciziFocusLost(evt);
            }
        });
        jTextFieldAkcizi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAkciziKeyPressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jTextFieldAkcizi, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 20, 5);
        jPanel2.add(jLabel4, gridBagConstraints);

        jTextFieldOther.setPreferredSize(new java.awt.Dimension(80, 20));
        jTextFieldOther.setInputVerifier(new imakante.com.InputDoubleVerifier());
        jTextFieldOther.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldOtherFocusLost(evt);
            }
        });
        jTextFieldOther.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldOtherKeyPressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jTextFieldOther, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldOtherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldOtherFocusLost
// TODO add your handling code here:
        p2 = Double.parseDouble(jTextFieldPrice2.getText());
        p_p2 = (100 * p2) / p0; 
        jTextFieldProcent2.setText(String.valueOf(p_p2));
    }//GEN-LAST:event_jTextFieldOtherFocusLost

    private void jTextFieldOtherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldOtherKeyPressed
// TODO add your handling code here:
       if(evt.getKeyCode()==evt.VK_ENTER)
        {
            try
            {
                p2 = Double.parseDouble(jTextFieldPrice2.getText());
                p_p2 = (100 * p2) / p0; 
                jTextFieldProcent2.setText(String.valueOf(p_p2));
                
            }
            catch(NumberFormatException e)
            {
               showMessage();
            }
         
        }
    }//GEN-LAST:event_jTextFieldOtherKeyPressed

    private void jTextFieldAkciziFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAkciziFocusLost
// TODO add your handling code here:
        p1 = Double.parseDouble(jTextFieldPrice1.getText());
        p_p1 = (100 * p1) / p0; 
        jTextFieldProcent1.setText(String.valueOf(p_p1));
        
    }//GEN-LAST:event_jTextFieldAkciziFocusLost

    private void jTextFieldAkciziKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAkciziKeyPressed
// TODO add your handling code here:
       
        if(evt.getKeyCode()==evt.VK_ENTER)
        {
            try
            {
                p1 = Double.parseDouble(jTextFieldPrice1.getText());
                p_p1 = (100 * p1) / p0; 
                jTextFieldProcent1.setText(String.valueOf(p_p1));
                
            }
            catch(NumberFormatException e)
            {
                showMessage();
            }
         
        }
    }//GEN-LAST:event_jTextFieldAkciziKeyPressed

    private void jTextFieldDDSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDDSKeyPressed
// TODO add your handling code here:
        if(jTextDostPrice.getText().length()>0)
        {
            jTextFieldPrice1.setEnabled(true);
            jTextFieldPrice2.setEnabled(true);
            jTextFieldPrice2.setEnabled(true);
            jTextFieldProcent3.setEnabled(true); 
            jTextFieldPrice3.setEnabled(true);
            jTextFieldProcent3.setEnabled(true);  
        }
    }//GEN-LAST:event_jTextFieldDDSKeyPressed

    private void jTextFieldDDSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDDSKeyReleased
// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDDSKeyReleased

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
// TODO add your handling code here:
       if(p0==0 && p1==0 && p2==0 && p3==0)
       {
           showMessage();
       }
       else
       {
        p0 = Double.parseDouble(jTextDostPrice.getText());
        p1 = Double.parseDouble(jTextFieldPrice1.getText());
        p2 = Double.parseDouble(jTextFieldPrice2.getText());
        p3 = Double.parseDouble(jTextFieldPrice3.getText());
        
        if(isNew)
        {
            myParent.getCountriesT().setNewPrice(id_price,p0,p1,p2,p3);
        }
        else
        {
            myParent.getCountriesT().updateProductPrice(id_price,p0,p1,p2,p3);
        }
        
       }
        
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed
    
    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new aeProductPriceFee(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldAkcizi;
    private javax.swing.JTextField jTextFieldDDS;
    private javax.swing.JTextField jTextFieldOther;
    // End of variables declaration//GEN-END:variables
 //--------------- My Variables
    private nom.FrmProduct myParent;
    private int id_price;
    private double p0=0,p1=0,p2=0,p3=0;
    private double p_p1,p_p2,p_p3;
    private boolean isNew = false;
 //---------------END My Variables
//---------------START MyFunction 
 

private void getDataByID()
{
    String prices[] = new String[4];
    
    prices = myParent.getCountriesT().getProductPrice(id_price);
    
    jTextDostPrice.setText(prices[0]);
    jTextFieldPrice1.setText(prices[1]);
    jTextFieldPrice2.setText(prices[2]);
    jTextFieldPrice3.setText(prices[3]);
    
    
    
}
private void showMessage()
{
     JOptionPane.showMessageDialog(this,"\u041c\u043e\u043b\u044f, \u0432\u044a\u0432\u0435\u0434\u0435\u0442\u0435 \u043a\u043e\u0440\u0435\u043a\u043d\u043e \u0434\u0430\u043d\u043d\u0438\u0442\u0435");
}
}// end class
