

package nom;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.DefaultTableCellRenderer;
public class aeProduct extends imakante.com.vcomponents.iDialog 
{
    
    /** Creates new form aeProduct */
    public aeProduct(imakante.com.vcomponents.iInternalFrame frame, boolean modal, boolean isnew, int selectComboBoxItem)// Test imakante.com.vcomponents.iInternalFrame frame
    {
        super(frame, modal); 
        this.myframe = frame;
        this.isNew = isnew; // opredelq dali zapisa sy6testwuwa v bazata;
        this.myParent = (nom.FrmProduct) frame;
        initComponents();
        getNavigatiionState();
        java.awt.Dimension dim = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        int x = (((dim.width)-(this.getSize().width))/2);
        int y = (((dim.height)-(this.getSize().height))/2);
        this.setLocation(x, y);
        splitGroups = myParent.getCountriesT().getProductGroup();
        for(int i=0;i<splitGroups.length;i++)
        {
            jComboBoxGroup.addItem(new String(splitGroups[i]));
            
        }
        
        if(selectComboBoxItem != 0)
          {
            
            selectComboBoxItem = getNewComboBoxIndex(selectComboBoxItem);
            
            jComboBoxGroup.setSelectedIndex(selectComboBoxItem);
          }
        
        // ------------Popylvane na colonite za opisanie
       splitNameOfColumn1 = myParent.getCountriesT().getProductDescriptionColumn();
       
        for(int i=0;i<splitNameOfColumn1.length;i++)
        {
            jComboBoxColumn1.addItem(new String(splitNameOfColumn1[i]));
            jComboBoxColumn2.addItem(new String(splitNameOfColumn1[i]));
            jComboBoxColumn3.addItem(new String(splitNameOfColumn1[i]));
        }
        
        
      // DefaultTableCellRenderer renderer =
      //          new DefaultTableCellRenderer();
        
        jTableDescription.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(jComboBoxColumn1));
       // jTableDescription.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(jComboBoxColumn2));
       // jTableDescription.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(jComboBoxColumn3));
          
        
        DefaultTableCellRenderer ff = new  DefaultTableCellRenderer() ;
        ff.add(jComboBoxColumn2);
        jTableDescription.getColumnModel().getColumn(0).setHeaderRenderer(ff);
        //jTableDescription.getColumnModel().getColumn(0).setCellRenderer(renderer);
        //jTableDescription.getColumnModel().getColumn(1).setCellRenderer(renderer);
        //jTableDescription.getColumnModel().getColumn(2).setCellRenderer(renderer);
        
        
        
        
        repaintComp();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelCod = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelBulstat = new javax.swing.JLabel();
        jLabelDanNomer = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelNM = new javax.swing.JLabel();
        jLabelTel = new javax.swing.JLabel();
        jLabelFax = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelWeb = new javax.swing.JLabel();
        jLabelMOL = new javax.swing.JLabel();
        jLabelOSO = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldCName = new javax.swing.JTextField();
        jTextFieldCod2 = new javax.swing.JTextField();
        jTextFieldSName = new javax.swing.JTextField();
        jTextFieldBarCod = new javax.swing.JTextField();
        jTextFieldFName = new javax.swing.JTextField();
        jTextFieldExpertSheet = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jTextFieldFee = new javax.swing.JTextField();
        jTextFieldPromoPrices = new javax.swing.JTextField();
        jTextFieldMaxPOP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldContragent = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCod1 = new javax.swing.JTextField();
        jComboBoxGroup = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jPanelDescription = new javax.swing.JPanel();
        jTableDescription = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButtonToBegin = new javax.swing.JButton();
        jButtonOneRowM = new javax.swing.JButton();
        jButtonOneRowP = new javax.swing.JButton();
        jButtonToEnd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMinProduct = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(675, 270));
        jLabelCod.setText("\u0413\u0440\u0443\u043f\u0430:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 5, 5);
        jPanel1.add(jLabelCod, gridBagConstraints);

        jLabelName.setText("\u0418\u043c\u0435:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 5);
        jPanel1.add(jLabelName, gridBagConstraints);

        jLabelBulstat.setText("\u041a\u043e\u04342");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabelBulstat, gridBagConstraints);

        jLabelDanNomer.setText("\u0418\u043c\u0435 \u043d\u0430 \u0441\u044a\u043e\u0442\u0432.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 5);
        jPanel1.add(jLabelDanNomer, gridBagConstraints);

        jLabelAddress.setText("\u041a\u044a\u0441\u043e \u0438\u043c\u0435:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 5);
        jPanel1.add(jLabelAddress, gridBagConstraints);

        jLabelNM.setText("\u0411\u0430\u0440\u043a\u043e\u0434:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabelNM, gridBagConstraints);

        jLabelTel.setText("\u0424\u0430\u043a\u0442\u044a\u0440\u043d\u043e \u0438\u043c\u0435:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 5);
        jPanel1.add(jLabelTel, gridBagConstraints);

        jLabelFax.setText("\u0415\u043a\u0441\u043f\u0435\u0440\u0442\u0435\u043d \u043b\u0438\u0441\u0442:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabelFax, gridBagConstraints);

        jLabelEmail.setText("\u0426\u0435\u043d\u0430:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 5);
        jPanel1.add(jLabelEmail, gridBagConstraints);

        jLabelWeb.setText("\u0422\u0430\u043a\u0441\u0438:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabelWeb, gridBagConstraints);

        jLabelMOL.setText("\u041f\u0440\u043e\u043c\u043e. \u0446\u0435\u043d\u0438:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 10, 5);
        jPanel1.add(jLabelMOL, gridBagConstraints);

        jLabelOSO.setText("\u041c\u0430\u0445 % \u043d\u0430 \u043e\u0442\u0441\u0442\u044a\u043f\u043a\u0430:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabelOSO, gridBagConstraints);

        jTextFieldName.setPreferredSize(new java.awt.Dimension(170, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFieldName, gridBagConstraints);

        jTextFieldCName.setPreferredSize(new java.awt.Dimension(170, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFieldCName, gridBagConstraints);

        jTextFieldCod2.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextFieldCod2.setPreferredSize(new java.awt.Dimension(170, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 20);
        jPanel1.add(jTextFieldCod2, gridBagConstraints);

        jTextFieldSName.setPreferredSize(new java.awt.Dimension(170, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFieldSName, gridBagConstraints);

        jTextFieldBarCod.setPreferredSize(new java.awt.Dimension(170, 20));
        jTextFieldBarCod.setInputVerifier(new imakante.com.InputIntegerVerifier());
        jTextFieldBarCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBarCodKeyPressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 20);
        jPanel1.add(jTextFieldBarCod, gridBagConstraints);

        jTextFieldFName.setPreferredSize(new java.awt.Dimension(170, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFieldFName, gridBagConstraints);

        jTextFieldExpertSheet.setPreferredSize(new java.awt.Dimension(170, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 20);
        jPanel1.add(jTextFieldExpertSheet, gridBagConstraints);

        jTextFieldPrice.setEditable(false);
        jTextFieldPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldPrice.setPreferredSize(new java.awt.Dimension(170, 20));
        jTextFieldPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPriceFocusLost(evt);
            }
        });
        jTextFieldPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPriceKeyPressed(evt);
            }
        });
        jTextFieldPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldPriceMousePressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFieldPrice, gridBagConstraints);

        jTextFieldFee.setEditable(false);
        jTextFieldFee.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldFee.setPreferredSize(new java.awt.Dimension(170, 20));
        jTextFieldFee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFeeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldFeeFocusLost(evt);
            }
        });
        jTextFieldFee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFeeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFeeKeyReleased(evt);
            }
        });
        jTextFieldFee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldFeeMousePressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 20);
        jPanel1.add(jTextFieldFee, gridBagConstraints);

        jTextFieldPromoPrices.setEditable(false);
        jTextFieldPromoPrices.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldPromoPrices.setPreferredSize(new java.awt.Dimension(170, 20));
        jTextFieldPromoPrices.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPromoPricesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPromoPricesFocusLost(evt);
            }
        });
        jTextFieldPromoPrices.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPromoPricesKeyPressed(evt);
            }
        });
        jTextFieldPromoPrices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldPromoPricesMousePressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jTextFieldPromoPrices, gridBagConstraints);

        jTextFieldMaxPOP.setPreferredSize(new java.awt.Dimension(170, 20));
        jTextFieldMaxPOP.setInputVerifier(new imakante.com.InputDoubleVerifier());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 20);
        jPanel1.add(jTextFieldMaxPOP, gridBagConstraints);

        jLabel1.setText("\u041a\u043e\u043d\u0442\u0440\u0430\u0433\u0435\u043d\u0442:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        jTextFieldContragent.setEditable(false);
        jTextFieldContragent.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldContragent.setPreferredSize(new java.awt.Dimension(170, 20));
        jTextFieldContragent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldContragentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldContragentFocusLost(evt);
            }
        });
        jTextFieldContragent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldContragentKeyPressed(evt);
            }
        });
        jTextFieldContragent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldContragentMousePressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 20);
        jPanel1.add(jTextFieldContragent, gridBagConstraints);

        jLabel2.setText("\u041a\u043e\u04341");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel2, gridBagConstraints);

        jTextFieldCod1.setPreferredSize(new java.awt.Dimension(170, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 20);
        jPanel1.add(jTextFieldCod1, gridBagConstraints);

        jComboBoxGroup.setPreferredSize(new java.awt.Dimension(170, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        jPanel1.add(jComboBoxGroup, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 100));
        jPanelDescription.setLayout(new javax.swing.BoxLayout(jPanelDescription, javax.swing.BoxLayout.X_AXIS));

        jPanelDescription.setBorder(javax.swing.BorderFactory.createTitledBorder("\u0420\u0430\u0437\u0444\u0430\u0441\u043e\u0432\u043a\u0430"));
        jPanelDescription.setPreferredSize(new java.awt.Dimension(230, 70));
        jTableDescription.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableDescription.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDescription.setAutoscrolls(false);
        jTableDescription.setPreferredSize(new java.awt.Dimension(200, 50));
        jTableDescription.setRowSelectionAllowed(false);
        //jComboBoxColumn1
        jPanelDescription.add(jTableDescription);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 20);
        jPanel4.add(jPanelDescription, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("\u041d\u0430\u0432\u0438\u0433\u0430\u0446\u0438\u044f"));
        jPanel3.setPreferredSize(new java.awt.Dimension(230, 70));
        jButtonToBegin.setText("<<");
        jButtonToBegin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToBeginActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonToBegin);

        jButtonOneRowM.setText("<");
        jButtonOneRowM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOneRowMActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonOneRowM);

        jButtonOneRowP.setText(">");
        jButtonOneRowP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOneRowPActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonOneRowP);

        jButtonToEnd.setText(">>");
        jButtonToEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToEndActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonToEnd);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 20);
        jPanel4.add(jPanel3, gridBagConstraints);

        jLabel3.setText("\u041c\u0438\u043d. \u043a\u043e\u043b.:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        jPanel4.add(jLabel3, gridBagConstraints);

        jTextFieldMinProduct.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        jPanel4.add(jTextFieldMinProduct, gridBagConstraints);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(263, 40));
        jButton1.setText("\u0421\u044a\u0445\u0440\u0430\u043d\u0438");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton1);

        jButton3.setText("\u0417\u0430\u0442\u0432\u043e\u0440\u0438");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFeeKeyPressed
// TODO add your handling code here:
        try
            {
              new aeProductPriceFee(myParent,true,myParent.getId_PF(),isNew).setVisible(true);
                
                
            } catch(Exception e)
            {
                e.printStackTrace();
            }
        repaintComp();
    }//GEN-LAST:event_jTextFieldFeeKeyPressed

    private void jTextFieldContragentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldContragentFocusLost
// TODO add your handling code here:
        jTextFieldContragent.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_jTextFieldContragentFocusLost

    private void jTextFieldContragentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldContragentFocusGained
// TODO add your handling code here:
         jTextFieldContragent.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
    }//GEN-LAST:event_jTextFieldContragentFocusGained

    private void jTextFieldContragentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldContragentKeyPressed
// TODO add your handling code here:
        showContein(1,true);
    }//GEN-LAST:event_jTextFieldContragentKeyPressed

    private void jTextFieldContragentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldContragentMousePressed
// TODO add your handling code here:
        showContein(1,true);
    }//GEN-LAST:event_jTextFieldContragentMousePressed

    private void jTextFieldFeeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFeeFocusGained
// TODO add your handling code here:
         jTextFieldFee.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
    }//GEN-LAST:event_jTextFieldFeeFocusGained

    private void jTextFieldFeeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFeeFocusLost
// TODO add your handling code here:
        jTextFieldFee.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_jTextFieldFeeFocusLost

    private void jTextFieldFeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFeeKeyReleased
// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFeeKeyReleased

    private void jTextFieldFeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldFeeMousePressed
// TODO add your handling code here:
        try
            {
              new aeProductPriceFee(myParent,true,myParent.getId_PF(),isNew).setVisible(true);
                
                
            } catch(Exception e)
            {
                e.printStackTrace();
            }
        repaintComp();
    }//GEN-LAST:event_jTextFieldFeeMousePressed

    private void jTextFieldPromoPricesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPromoPricesFocusLost
// TODO add your handling code here:
        jTextFieldPromoPrices.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_jTextFieldPromoPricesFocusLost

    private void jTextFieldPromoPricesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPromoPricesFocusGained
// TODO add your handling code here:
         jTextFieldPromoPrices.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
    }//GEN-LAST:event_jTextFieldPromoPricesFocusGained

    private void jTextFieldPromoPricesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPromoPricesMousePressed
// TODO add your handling code here:
         try
            {
              promoDialog = new aeProductPricePromotion(myParent,true,myParent.getId_PPP(),isNew);
              promoDialog.setVisible(true);
                
                
            } catch(Exception e)
            {
                e.printStackTrace();
            }
         repaintComp();
    }//GEN-LAST:event_jTextFieldPromoPricesMousePressed

    private void jTextFieldPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPriceFocusLost
// TODO add your handling code here:
        jTextFieldPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_jTextFieldPriceFocusLost

    private void jTextFieldPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPriceFocusGained
// TODO add your handling code here:
        jTextFieldPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
    }//GEN-LAST:event_jTextFieldPriceFocusGained

    private void jTextFieldPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPriceKeyPressed
// TODO add your handling code here:
       
            
         try
            {
              new aeProductPrice(myParent,true,myParent.getId_PP(),isNew).setVisible(true);
                
                
            } catch(Exception e)
            {
                e.printStackTrace();
            }
        
       repaintComp(); 
    }//GEN-LAST:event_jTextFieldPriceKeyPressed

    private void jTextFieldPriceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPriceMousePressed
// TODO add your handling code here:
         try
            {
              new aeProductPrice(myParent,true,myParent.getId_PP(),isNew).setVisible(true);
                
                
            } catch(Exception e)
            {
                e.printStackTrace();
            }
         repaintComp();
    }//GEN-LAST:event_jTextFieldPriceMousePressed

    //
    private void jButtonToEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToEndActionPerformed
// TODO add your handling code here:
         isNew = false;
         myParent.mTableEnd();
         jButtonToEnd.setEnabled(false);
         jButtonOneRowP.setEnabled(false);
         jButtonToEnd.repaint();
         jButtonOneRowP.repaint();
        
         
        jButtonToBegin.setEnabled(true);
        jButtonOneRowM.setEnabled(true);
        jButtonToBegin.repaint();
        jButtonOneRowM.repaint();
      
       
        repaintComp();
    }//GEN-LAST:event_jButtonToEndActionPerformed

    private void jButtonOneRowPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOneRowPActionPerformed
// TODO add your handling code here:
         isNew = false;
         myParent.mOneRowPlus();
        if(myParent.isAtEnd())
        {
         jButtonToEnd.setEnabled(false);
         jButtonOneRowP.setEnabled(false);
         jButtonToEnd.repaint();
         jButtonOneRowP.repaint();
           
        }
         
        jButtonToBegin.setEnabled(true);
        jButtonOneRowM.setEnabled(true);
        jButtonToBegin.repaint();
        jButtonOneRowM.repaint();
        repaintComp();  
    }//GEN-LAST:event_jButtonOneRowPActionPerformed

    private void jButtonOneRowMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOneRowMActionPerformed
// TODO add your handling code here:
         isNew = false;
         myParent.mOneRowMinus();
        if(myParent.isAtBegining())
        {
           jButtonToBegin.setEnabled(false);
        jButtonOneRowM.setEnabled(false);
        jButtonToBegin.repaint();
        jButtonOneRowM.repaint();
            
        }
        jButtonToEnd.setEnabled(true);
         jButtonOneRowP.setEnabled(true);
         jButtonToEnd.repaint();
         jButtonOneRowP.repaint();
        repaintComp();
    }//GEN-LAST:event_jButtonOneRowMActionPerformed

    private void jButtonToBeginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToBeginActionPerformed
// TODO add your handling code here:
        isNew = false;
        myParent.mTableBegining();
        
        jButtonToBegin.setEnabled(false);
        jButtonOneRowM.setEnabled(false);
        jButtonToBegin.repaint();
        jButtonOneRowM.repaint();
        
        jButtonToEnd.setEnabled(true);
         jButtonOneRowP.setEnabled(true);
         jButtonToEnd.repaint();
         jButtonOneRowP.repaint();
       
        repaintComp();
    }//GEN-LAST:event_jButtonToBeginActionPerformed

    private void jTextFieldPromoPricesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPromoPricesKeyPressed
// TODO add your handling code here:
        try
            {
              new aeProductPricePromotion(myParent,true,myParent.getId_PPP(),isNew).setVisible(true);
                
                
            } catch(Exception e)
            {
                e.printStackTrace();
            }
   
        repaintComp();
    }//GEN-LAST:event_jTextFieldPromoPricesKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        if(isNew) // zapisa NE sy6testvuva v bazata!!
        {
            if((myParent.getId_Group()==-1) | (myParent.getId_PF()==-1) |
                    (myParent.getId_PD()==-1) | (myParent.getId_PP()==-1) | (myParent.getId_PPP()==-1))
            {
                // syob6tenie da se vuvede naseleneto mqsto, MOL i OSO;
                   showMessage();
               
            }
            else
            {
              
                if(setAllVariables())
                {
                myParent.getCountriesT().insertRow(myParent.getId_PM(),myParent.getId_PPP(),myParent.getId_PP(),
                                                   myParent.getId_PF(),myParent.getId_Group(),myParent.getId_PD(),
                                                   myParent.getNamePM(),myParent.getSNamePM(),myParent.getFNamePM(),
                                                   myParent.getCNamePM(),myParent.getMax_POP(),myParent.getFlag(),
                                                   myParent.getExpertSheet(),myParent.getBarCod(),myParent.getCod1(),
                                                   myParent.getCod2());
                }
                else
                {
                    showMessage();
                    jComboBoxGroup.setFocusable(true);
                    jComboBoxGroup.setSelectedIndex(0);
                }
                
            }
        }
        else  // zapisa  sy6testvuva v bazata!!
        {
                if(setAllVariables())
                {
                
                myParent.getCountriesT().updateRow(myParent.getId_PM(),myParent.getId_PPP(),myParent.getId_PP(),
                                                   myParent.getId_PF(),myParent.getId_Group(),myParent.getId_PD(),
                                                   myParent.getNamePM(),myParent.getSNamePM(),myParent.getFNamePM(),
                                                   myParent.getCNamePM(),myParent.getMax_POP(),myParent.getFlag(),
                                                   myParent.getExpertSheet(),myParent.getBarCod(),myParent.getCod1(),
                                                   myParent.getCod2());
                }
                else
                {
                    showMessage();
                    jComboBoxGroup.setFocusable(true);
                    jComboBoxGroup.setSelectedIndex(0);
                }
            
        }
    //  jButton3.doClick(); // zatvarq se aeProsuct
      myParent.refreshTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldBarCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBarCodKeyPressed
// TODO add your handling code here:
 // pri natiskane na F7 6te se izvikva aContragent, za izbor na naseleno mqsto ot bazata danni
      
    }//GEN-LAST:event_jTextFieldBarCodKeyPressed
    
    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aeProduct(new JFrame(),true,true,1).setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonOneRowM;
    private javax.swing.JButton jButtonOneRowP;
    private javax.swing.JButton jButtonToBegin;
    private javax.swing.JButton jButtonToEnd;
    private javax.swing.JComboBox jComboBoxGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelBulstat;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelDanNomer;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFax;
    private javax.swing.JLabel jLabelMOL;
    private javax.swing.JLabel jLabelNM;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelOSO;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JLabel jLabelWeb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelDescription;
    private javax.swing.JTable jTableDescription;
    private javax.swing.JTextField jTextFieldBarCod;
    private javax.swing.JTextField jTextFieldCName;
    private javax.swing.JTextField jTextFieldCod1;
    private javax.swing.JTextField jTextFieldCod2;
    private javax.swing.JTextField jTextFieldContragent;
    private javax.swing.JTextField jTextFieldExpertSheet;
    private javax.swing.JTextField jTextFieldFName;
    private javax.swing.JTextField jTextFieldFee;
    private javax.swing.JTextField jTextFieldMaxPOP;
    private javax.swing.JTextField jTextFieldMinProduct;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldPromoPrices;
    private javax.swing.JTextField jTextFieldSName;
    // End of variables declaration//GEN-END:variables
 //--------------- My Variables
   private FrmProduct myParent;
   private javax.swing.JComboBox jComboBoxColumn1 = new javax.swing.JComboBox();
   private javax.swing.JComboBox jComboBoxColumn2 = new javax.swing.JComboBox();
   private javax.swing.JComboBox jComboBoxColumn3 = new javax.swing.JComboBox();
   private showContentsCon_Gr showContein;
   private imakante.com.vcomponents.iInternalFrame myframe;
   private String splitGroups[] = null;
   private String splitNameOfColumn1[] = null;
   private String splitNameOfColumn2[] = null;
   private String splitNameOfColumn3[] = null;
   private aeProductPricePromotion promoDialog;
   boolean isNew; // za opredelqne dali zapisa e 4isto nov, t.e dali ne sy6testva b bazata
 //---------------END My Variables
//---------------START MyFunction 
 private void getNavigatiionState() // ok
    {
    if(myParent.isAtBegining())
    {
        jButtonToBegin.setEnabled(false);
        jButtonOneRowM.setEnabled(false);
        jButtonToBegin.repaint();
        jButtonOneRowM.repaint();
    }
    if(myParent.isAtEnd())
    {
        jButtonToEnd.setEnabled(false);
        jButtonOneRowP.setEnabled(false);
         jButtonToEnd.repaint();
        jButtonOneRowP.repaint();
    }
}
 private void repaintComp() // Test
    {
   if(!isNew)
   {
   jTextFieldName.setText(myParent.getNamePM());
   jTextFieldCName.setText(myParent.getCNamePM());
   jTextFieldSName.setText(myParent.getSNamePM());
   jTextFieldFName.setText(myParent.getFNamePM());
   jTextFieldBarCod.setText(String.valueOf(myParent.getBarCod()));
   
   jTextFieldCod1.setText(myParent.getCod1());
   jTextFieldCod2.setText(myParent.getCod2());
   jTextFieldMaxPOP.setText(String.valueOf(myParent.getMax_POP()));
   jTextFieldExpertSheet.setText(myParent.getExpertSheet());
   jTextFieldMinProduct.setText(String.valueOf(myParent.getMinProduct()));
     
   
   }
  if(isNew)
  {
   
  }  
   
  if((myParent.getId_PD()!=0)) // n_product_description
   {
   String description[][] = myParent.getCountriesT().getDescription(myParent.getId_PD());
   
   
       int newItem = getNewComboBoxColumnIndex(Integer.parseInt(description[0][0]));
       jComboBoxColumn1.setSelectedIndex(newItem); 
       
        newItem = getNewComboBoxColumnIndex(Integer.parseInt(description[1][0]));
       jComboBoxColumn2.setSelectedIndex(newItem); 
       
        newItem = getNewComboBoxColumnIndex(Integer.parseInt(description[2][0]));
       jComboBoxColumn3.setSelectedIndex(newItem); 
       
   
        jTableDescription.setValueAt(new String(description[0][1]),1,0);
        jTableDescription.setValueAt(new String(description[1][1]),1,1);
        jTableDescription.setValueAt(new String(description[2][1]),1,2);
    
    
   }
   if(myParent.getId_PF()!=0) 
   {
   String  fee[] = myParent.getCountriesT().getProdictFee(myParent.getId_PF());
   jTextFieldFee.setText(fee[0]);
   }
   if (myParent.getId_PP()!=0)
   {
   String price[] = myParent.getCountriesT().getProductPrice(myParent.getId_PP());
   jTextFieldPrice.setText(price[0]);
   }
   if (myParent.getId_PPP()!=0)
   {
   String promotion_price[] = myParent.getCountriesT().getProductPromotionPrice(myParent.getId_PPP());
   jTextFieldPromoPrices.setText(promotion_price[0]);
   }
  
   if (myParent.getId_Group()!=0) // ????? drug varioan da se izmisli
   {
     jComboBoxGroup.setSelectedItem(getNewComboBoxIndex(myParent.getId_Group()));
   }
   
   /*{
   String contragent = myParent.getCountriesT().getProductContragent(myParent.getId_PM());
   jTextFieldContragent.setText(contragent);
   }*/
   
} 
 private void showContein(int con_gr, boolean isEditalble) // test
 {
      try
            {
         
             java.sql.ResultSet r1 = myParent.getCountriesT().getShowContein();
             showContein = new showContentsCon_Gr(myframe,true,r1,myParent.getCountriesT().getConn());
             showContein.setVisible(true);
                
            } catch(Exception e)
            {
                e.printStackTrace();
            }
     
     
 }
 private int getNewComboBoxIndex(int oldindex) //OK
{ 
    int newindex= 0;
    for(int i = 0; i < myParent.getCountriesT().getIndexConnOfId().length; i++)
       {
        if(myParent.getCountriesT().getIndexConnOfId()[i]==oldindex)
          {
           newindex = i;
           break;
          }
      }
    return newindex;
}

private int getNewComboBoxColumnIndex(int oldindex) //OK
{ 
    int newindex= 0;
    for(int i = 0; i < myParent.getCountriesT().getIndexConnOfIdColumn().length; i++)
       {
        if(myParent.getCountriesT().getIndexConnOfIdColumn()[i]==oldindex)
          {
           newindex = i;
           break;
          }
      }
    return newindex;
}
 private boolean  setAllVariables()
 { 
     boolean isOk= true;
          
     myParent.setNamePM(jTextFieldName.getText());
     myParent.setSNamePM(jTextFieldSName.getText());
     myParent.setFNamePM(jTextFieldFName.getText());
     myParent.setCNamePM(jTextFieldCName.getText());
     myParent.setCod1(jTextFieldCod1.getText());
     myParent.setCod2(jTextFieldCod2.getText());
     myParent.setExpertSheet(jTextFieldExpertSheet.getText());
     try
     {
     myParent.setBarCod(Integer.parseInt(jTextFieldBarCod.getText()));
     myParent.setMax_POP(Integer.parseInt(jTextFieldMaxPOP.getText()));
     myParent.setMinProduct(Integer.parseInt(jTextFieldMinProduct.getText()));
     }
     catch(Exception e)
     {
       showMessage();  
       isOk = false;
     }
     if( (myParent.getId_PF() ==0) | (myParent.getId_Group()==0) | (myParent.getId_PP()==0) |
             (myParent.getId_PPP() ==0)) //(myParent.getId_PD()==0) |
     {
        isOk = false;
     }
     return isOk;
 }
 private void showMessage()
{
     JOptionPane.showMessageDialog(this,"\u041c\u043e\u043b\u044f, \u0432\u044a\u0432\u0435\u0434\u0435\u0442\u0435 \u043a\u043e\u0440\u0435\u043a\u043d\u043e \u0434\u0430\u043d\u043d\u0438\u0442\u0435");
     
    
}
}// end class

