/*
 *0.FrmContragent.java
 *
 * 1.contragentDB - cannection to SQL server;
 * 2.aeContragent - edit/insert/search element of table;
 * 3.showAddressContragent - select address (City,province, post code);
 * 4.showNameOfMOL_OSO - select names (first name, surname last name);
 */

package nom;



import java.awt.event.WindowListener;
import java.awt.print.PrinterException;
import java.sql.*;
import imakante.com.*;
import imakante.com.vcomponents.*;
import javax.print.PrintException;
import javax.swing.*;
import java.text.MessageFormat;

public class FrmContragent extends imakante.com.vcomponents.iInternalFrame implements WindowListener
{
    
    /** Creates new form FrmContragent */
    public FrmContragent(String title, int flag) // // TEST ----> da se dobavi: imakante.com.vcomponents.iFrame frame,
    {
        super(title);
      // myframe = frame; 
        prepareConn();     // zapazva connection
        this.flag = flag; //  za da rabotim samo s opredeleni zapisi ima6ti syotvetniq fag
        constructGroupDB(); // inicializira class otgovarq6t za vryzkata s DB
        initTable();
        initComponents();
        fr.addWindowListener(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonNew = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jButtonPrintReport = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jButtonDeleteAll = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 834, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 10, Short.MAX_VALUE)
        );
        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.getViewport().add(table);
        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(801, 37));
        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 834, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 33, Short.MAX_VALUE)
        );
        jPanel2.add(jPanel4, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(801, 37));
        jButtonNew.setText("\u041d\u043e\u0432");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonNew);

        jButtonEdit.setText("\u0420\u0435\u0434\u0430\u043a\u0446\u0438\u044f");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonEdit);

        jButtonPrint.setText("\u041f\u0435\u0447\u0430\u0442");
        jPanel3.add(jButtonPrint);

        jButtonPrintReport.setText("\u041f\u0435\u0447\u0430\u0442 \u0440\u0435\u043f\u043e\u0440\u0442");
        jPanel3.add(jButtonPrintReport);

        jButtonDelete.setText("\u0418\u0437\u0442\u0440\u0438\u0432\u0430\u043d\u0435");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonDelete);

        jButtonRefresh.setText("\u0412\u0441\u0438\u0447\u043a\u0438 \u0437\u0430\u043f\u0438\u0441\u0438");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonRefresh);

        jButtonDeleteAll.setText("\u0418\u0437\u0442\u0440\u0438\u0432\u0430\u043d\u0435 \u043d\u0430 \u0442\u0430\u0431\u043b\u0438\u0446\u0430");
        jPanel3.add(jButtonDeleteAll);

        jButtonClose.setText("\u0417\u0430\u0442\u0432\u0430\u0440\u044f\u043d\u0435");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonClose);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
// TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
// TODO add your handling code here:
        if(table.getSelectedRow() != -1)
        {
            setRow(table.getSelectedRow());
            setId((Integer)table.getValueAt(getRow(),0));
            countriesT.deleteRow(getId());
            refreshTable();
        }
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
// TODO add your handling code here:
        setCod("");
        setName("");
        setBulstat("");
        setDanNomer("");
        setAddress("");
        setID_NM(-1);
        setTel("");
        setFax("");
        setEmail("");
        setWeb("");
        setID_MOL(-1);
        setID_OSO(-1);
        
     
       
         try
            {
                nom.aeContragent dialog = new nom.aeContragent(this, true,true);
                dialog.setVisible(true);
                
            } catch(Exception e)
            {
                e.printStackTrace();
            }
        refreshTable(); 
        
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
// TODO add your handling code here:
        if (table.getSelectedRow() != -1) 
        { 
            
            setRow(table.getSelectedRow());
            if(getRow()==0){
                setAtBegining(true);
            }
            if(getRow()==getMaxRow()){
                setAtEnd(true);
            }
            setId((Integer) table.getValueAt(getRow(), 0));
            setCod((String) table.getValueAt(getRow(), 1));
            setName((String) table.getValueAt(getRow(), 2));
            setBulstat((String)table.getValueAt(getRow(),3));
            setDanNomer((String)table.getValueAt(getRow(),4));
            setAddress((String)table.getValueAt(getRow(),5));
            setID_NM((Integer) table.getValueAt(getRow(), 6));
            setTel((String) table.getValueAt(getRow(), 11));
            setFax((String) table.getValueAt(getRow(), 12));
            setEmail((String) table.getValueAt(getRow(), 13));
            setWeb((String) table.getValueAt(getRow(), 14));
            setID_MOL((Integer) table.getValueAt(getRow(), 15));
            setID_OSO((Integer) table.getValueAt(getRow(), 17));
            
            
            try
            {
                nom.aeContragent dialog = new nom.aeContragent(this, true,false);
                dialog.setVisible(true);
                
            } catch(Exception e)
            {
                e.printStackTrace();
            }
        }else{
            
        }
        
    }//GEN-LAST:event_jButtonEditActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
               FrmContragent frCN =   new FrmContragent("ttt",0);
                fr.add(frCN);
                frCN.setVisible(true);
                fr.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDeleteAll;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonPrintReport;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
//--------------- My Variables
    private  boolean atBegining=false;
    private  boolean atEnd = false;
    private int row;
   
    private int id,id_nm,id_mol,id_oso,flag;
    private String cod,name,bull,dan,address,tel,fax,email,web;
    private imakante.com.vcomponents.iFrame myframe;
    private java.sql.Connection conn;
    private  java.sql.ResultSet rs; 
    private contragentDB countriesT;
    private  imakante.com.CustomTableModel model;
    private  imakante.com.CustomTable table; 
    private java.sql.Connection ccc;  // samo za testvaneto
    private  static JFrame fr = new JFrame("test");
    private String User="javauser";  // vremenna promenliva za test
    private String Pass="javadude";  // vremenna promenliva za test
    private String Url = "jdbc:mysql://127.0.0.1:3306/frmtest";  // vremenna promenliva za test
 
    
//---------------END My Variables
 //---------------START MyFunction
    
 private void prepareConn() //TEST
    {
      // samo za testovate ------------
      try
         {
          Class.forName("com.mysql.jdbc.Driver");
           
           ccc = DriverManager.getConnection(Url, User, Pass);
           conn = ccc;
          
         }
         catch(Exception e)
         {
             e.printStackTrace();
         }
      //
      /* try
       {
            setConn(myframe.getConn());
       }
       catch(Exception e)
       {
       e.printStackTrace();
       }*/
  }
private void constructGroupDB() // ok
    {
        try
        {
            
         countriesT = new nom.contragentDB(conn,flag);
        }
        catch(Exception e)
        
        {
            e.printStackTrace();
        }
        System.out.println("ot construct object");
    }
private void initTable() //OK  -- !!ima za dovyr6wane - skrivane na koloni!!
    {
      try
        {
            countriesT.setFlag(flag);
            rs = countriesT.getTable();
            model = new imakante.com.CustomTableModel(conn,rs, null);
            table = new imakante.com.CustomTable(model);
            // da se napravqt skriti kolona "id" 
        }
       catch(Exception e)
       {
           e.printStackTrace();
       }
       table.requestFocus();
       try
        {
          table.setEditingRow(0);
       } 
        catch(Exception ex) 
        {
        
        }
  }
       
 public void windowOpened(java.awt.event.WindowEvent e)
  {
   }
  public void windowClosing(java.awt.event.WindowEvent e) // colose frame`s windows
   {
        System.exit(1);
   }
        
  public void windowClosed(java.awt.event.WindowEvent e)
   {
        System.out.println("windowClosed");
   }
  public void windowIconified(java.awt.event.WindowEvent e)
   {
   }
  public void windowDeiconified(java.awt.event.WindowEvent e)
   {
   }
  public void windowActivated(java.awt.event.WindowEvent e)
   {
   }
  public void windowDeactivated(java.awt.event.WindowEvent e) 
   {
   
   }   
  
   public  void setRow(int val) //OK
    {
        row = val;
    }
   public int getRow() //ok
   {
       return row;
   }
    public  void setAtBegining(boolean aAtBegining)//OK
  {
        atBegining = aAtBegining;
    }
    
    public  boolean isAtEnd()//OK
    {
        return atEnd;
    }
    
    public  void setAtEnd(boolean aAtEnd) //OK
    {
        atEnd = aAtEnd;
    } 
     private int  getMaxRow() //OK
   {
        int i = 0;
        i  = table.getRowCount() - 1;
        return i;
   }
    public void setId(int ID) 
    {
        this.id = ID;
    }
    public int getId() 
    {
        return id;
    }
  public void setCod(String COD) 
    {
        this.cod = COD;
    }
    public String getCod() 
    {
        return cod;
    }
    public void setName(String Name) 
    {
        this.name = Name;
    }
    public String getName() 
    {
        return name;
    }
    public void setBulstat(String bul)
    {
        this.bull = bul;
    }
    public String getBulstat()
    {
        return bull;
    }
    public void setDanNomer(String dannomer)
    {
        this.dan = dannomer;
    }
    public String getDanNomer()
    {
        return dan;
    }
    public void setAddress(String address)
    {
        this.address = address;
    }
    public String getAddress()
    {
        return address;
    }
    public void setID_NM(int nm)
    {
        this.id_nm = nm;
    }
    public int getID_NM()
    {
        return id_nm;
    }
    public void setTel(String tel)
    {
        this.tel = tel;
    }
    public String getTel()
    {
        return tel;
    }
    public void setFax(String fax)
    {
        this.fax = fax;
    }
    public String getFax()
    {
        return fax;
    }
    public void setEmail(String email)
    {
        this.email = email;
    }
    public String getEmail()
    {
        return email;
    }
    public void setWeb(String web)
    {
        this.web = web;
    }
    public String getWeb()
    {
        return web;
    }
    public void setID_MOL(int mol)
    {
        this.id_mol = mol;
    }
    public int getID_MOL()
    {
        return id_mol;
    }
    public void setID_OSO(int oso)
    {
        this.id_oso = oso;
    }
    public int getID_OSO()
    {
        return id_oso;
    } 
   public void setCountriesT(contragentDB ccc) 
   {
       countriesT = ccc;
   }
   public contragentDB getCountriesT()
   {
       return countriesT;
   }
    protected  void refreshTable() //OK
  {
        jScrollPane1.remove(table);
        rs = countriesT.getTable();
        model = new imakante.com.CustomTableModel(conn, rs, null);
        table = new imakante.com.CustomTable(model);
        jScrollPane1.getViewport().add(table);
        jScrollPane1.repaint();
        
    }
}// end class
