CREATE TABLE `mida`.`updates_db` (
  `id_updates` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `developer` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `vid` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `build` VARCHAR(45) NOT NULL DEFAULT 0,
  `ver` VARCHAR(45) NOT NULL DEFAULT 0,
  `zad` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `sql_string` TEXT,
  `tm_st` TIMESTAMP NOT NULL,
  `file_url_uri` VARCHAR(200) NOT NULL,
  PRIMARY KEY(`id_updates`)
)
ENGINE = MYISAM;