/*
 * acc_main.java
 *
 * Created on Неделя, 2005, Октомври 9, 5:14
 */

package acc;

/**
 *
 * @author  Radoslav
 */
public class acc_main extends javax.swing.JFrame {
    
    /** Creates new form acc_main */
    public acc_main() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProgram = new javax.swing.JMenu();
        menuDoc = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        menuProgram.setText("\u041f\u0440\u043e\u0433\u0440\u0430\u043c\u0430");
        jMenuBar1.add(menuProgram);

        menuDoc.setText("\u0412\u044a\u0432\u0435\u0436\u0434\u0430\u043d\u0435 \u0434\u0430\u043d\u043d\u0438");
        jMenuBar1.add(menuDoc);

        jMenu1.setText("\u041d\u043e\u043c\u0435\u043d\u043a\u043b\u0430\u0442\u0443\u0440\u0438");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("\u0421\u043f\u0440\u0430\u0432\u043a\u0438");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acc_main().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuDoc;
    private javax.swing.JMenu menuProgram;
    // End of variables declaration//GEN-END:variables
    
}
